# -*- coding: utf-8 -*-
"""
Contenido legal para las páginas de Política de Privacidad y Términos de Uso.

Estructura en dos capas:
- IDIOMAS: el texto compartido (qué datos se recopilan, para qué, cookies,
  secciones de términos, etc.) en cada uno de los 6 idiomas que soporta la
  app. Este contenido NO depende del país — es igual en español para España
  que para Latinoamérica, por ejemplo.
- REGIONES: lo que SÍ cambia por país/región — la ley de protección de datos
  aplicable, la autoridad de control, los derechos exactos del titular, y la
  base legal del tratamiento. Cada región apunta a un idioma de IDIOMAS.

⚠️ AVISO IMPORTANTE (léelo, Diego): este contenido está redactado con cuidado
y orientado a los marcos legales reales de cada región, pero NO es un
documento certificado por un abogado ni sustituye asesoría legal real. Antes
de operar con clientes reales pagando dinero real, especialmente en Europa
(RGPD) y California (CCPA) donde las multas pueden ser altas, vale la pena
una revisión profesional — aunque sea una consulta puntual y barata.
"""

IDIOMAS = {
    "es": {
        "lang_attr": "es",
        "volver": "← Volver",
        "p_titulo": "🔒 Política de Privacidad",
        "p_subtitulo": "datos personales que recopilamos y cómo los usamos",
        "p_intro": "Esta política explica qué información personal recopila {nombre} cuando usted completa nuestro formulario de contacto, y cómo la usamos para atenderle mejor.",
        "p_resp_titulo": "1. Responsable del tratamiento",
        "p_resp_texto": "{nombre} es responsable de los datos personales que usted comparte a través de nuestro formulario de contacto y nuestro portal de seguimiento.",
        "p_datos_titulo": "2. Datos que recopilamos",
        "p_datos_intro": "Cuando completa nuestro formulario, recopilamos:",
        "p_datos_lista": ["Nombre completo", "Número de teléfono", "Correo electrónico (si lo proporciona)", "Zona de interés y presupuesto aproximado", "Cualquier mensaje adicional que nos escriba"],
        "p_finalidad_titulo": "3. Para qué usamos sus datos",
        "p_finalidad_lista": ["Contactarlo para darle seguimiento a su búsqueda de propiedad", "Recomendarle propiedades que coincidan con lo que busca", "Coordinar y recordarle visitas agendadas a propiedades", "Enviarle actualizaciones relevantes sobre su proceso de búsqueda"],
        "p_comparticion_titulo": "4. Con quién compartimos sus datos",
        "p_comparticion_texto": "Sus datos se procesan a través de nuestro sistema de gestión (CRM) para uso exclusivo de nuestro equipo de ventas. No vendemos su información a terceros para fines de mercadeo ajenos a nuestra relación comercial con usted. Podemos usar herramientas de correo electrónico y WhatsApp para comunicarnos directamente con usted.",
        "p_conservacion_titulo": "5. Cuánto tiempo conservamos sus datos",
        "p_conservacion_texto": "Conservamos su información mientras exista una relación comercial activa o potencial, o hasta que usted solicite su eliminación.",
        "p_cookies_titulo": "6. Cookies y sesión",
        "p_cookies_texto": "Nuestro portal de seguimiento usa una cookie de sesión técnica necesaria para que la página funcione correctamente. No usamos cookies de rastreo publicitario.",
        "p_cambios_titulo": "7. Cambios a esta política",
        "p_cambios_texto": "Podemos actualizar esta política ocasionalmente. La fecha de la versión vigente siempre estará disponible en esta misma página.",
        "p_seguridad_titulo": "Medidas de seguridad",
        "p_seguridad_texto": "Su información se transmite mediante conexión cifrada (HTTPS) y se almacena en una base de datos con controles de acceso. Las contraseñas de nuestro personal se guardan cifradas, nunca en texto plano, y el acceso a sus datos está limitado al personal autorizado de {nombre}.",
        "p_menores_titulo": "Menores de edad",
        "p_menores_texto": "Nuestros servicios están dirigidos a personas mayores de edad. No recopilamos intencionalmente datos de menores. Si detectamos que un menor nos proporcionó datos sin el consentimiento de sus padres o tutores, los eliminaremos.",
        "p_minimizacion_titulo": "Minimización de datos",
        "p_minimizacion_texto": "Solo solicitamos los datos estrictamente necesarios para darle seguimiento a su búsqueda de propiedad. No le pedimos información sensible (salud, religión, orientación sexual, etc.) y le pedimos evitar incluir ese tipo de datos en el campo de mensaje.",
        "p_brecha_titulo": "Notificación de incidentes de seguridad",
        "p_brecha_texto": "En caso de una brecha de seguridad que comprometa sus datos personales, nos comprometemos a notificarle a usted y a la autoridad competente conforme a los plazos que exija la ley aplicable.",
        "p_ejercicio_titulo": "Cómo ejercer sus derechos",
        "p_ejercicio_texto": "Para ejercer cualquiera de sus derechos, escríbanos usando los datos de contacto al final de esta página, indicando claramente su solicitud. Le responderemos {plazo}.",
        "p_contacto_label": "📩 ¿Preguntas sobre sus datos? Contacte a {nombre} directamente",
        "p_whatsapp_txt": "por WhatsApp al",
        "p_correo_txt": "o al correo",
        "t_titulo": "📋 Términos de Uso",
        "t_subtitulo": "condiciones para usar nuestro formulario y portal de seguimiento",
        "t_intro": "Al completar nuestro formulario de contacto o usar nuestro portal de seguimiento, usted acepta los siguientes términos.",
        "t_secciones": [
            ("1. Sobre este servicio", "{nombre} pone a su disposición un formulario de contacto y un portal de seguimiento para facilitar su búsqueda de propiedades y la comunicación con nuestro equipo de asesores."),
            ("2. Uso adecuado", "Usted se compromete a proporcionar información veraz y actualizada al completar nuestro formulario. Nos reservamos el derecho de no dar seguimiento a solicitudes con información falsa o incompleta."),
            ("3. Sin garantía de disponibilidad", "Las propiedades mostradas en nuestro portal están sujetas a disponibilidad y pueden cambiar sin previo aviso. No garantizamos que una propiedad de su interés siga disponible al momento de contactarlo."),
            ("4. Comunicación", "Al proporcionarnos su teléfono y/o correo electrónico, usted autoriza a que nuestro equipo se comunique con usted por esos medios (incluyendo WhatsApp y correo electrónico) para dar seguimiento a su solicitud."),
            ("5. Visitas agendadas", "Si agenda una visita a través de nuestro portal, usted se compromete a confirmar o reagendar con anticipación si no puede asistir, para no afectar la disponibilidad de nuestros asesores."),
            ("6. Propiedad del contenido", "El contenido, fotos y descripciones de las propiedades publicadas son propiedad de {nombre} y no pueden reproducirse sin autorización."),
            ("7. Cambios a estos términos", "Podemos actualizar estos términos ocasionalmente. La versión vigente siempre estará disponible en esta misma página."),
        ],
        "t_contacto_label": "📩 ¿Dudas sobre estos términos? Contacte a {nombre} directamente",
        "selector_titulo": "Selecciona tu país o región",
        "selector_sub": "El contenido legal cambia según el marco de protección de datos que le aplique.",
    },
    "en": {
        "lang_attr": "en",
        "volver": "← Back",
        "p_titulo": "🔒 Privacy Policy",
        "p_subtitulo": "personal data we collect and how we use it",
        "p_intro": "This policy explains what personal information {nombre} collects when you fill out our contact form, and how we use it to serve you better.",
        "p_resp_titulo": "1. Data Controller",
        "p_resp_texto": "{nombre} is responsible for the personal data you share through our contact form and follow-up portal.",
        "p_datos_titulo": "2. Data We Collect",
        "p_datos_intro": "When you fill out our form, we collect:",
        "p_datos_lista": ["Full name", "Phone number", "Email address (if provided)", "Area of interest and approximate budget", "Any additional message you send us"],
        "p_finalidad_titulo": "3. How We Use Your Data",
        "p_finalidad_lista": ["To contact you and follow up on your property search", "To recommend properties matching what you're looking for", "To coordinate and remind you of scheduled property visits", "To send you relevant updates about your search process"],
        "p_comparticion_titulo": "4. Who We Share Your Data With",
        "p_comparticion_texto": "Your data is processed through our internal management system (CRM) for exclusive use by our sales team. We do not sell your information to third parties for marketing purposes unrelated to our business relationship with you. We may use email and WhatsApp tools to communicate with you directly.",
        "p_conservacion_titulo": "5. How Long We Keep Your Data",
        "p_conservacion_texto": "We retain your information for as long as there is an active or potential business relationship, or until you request its deletion.",
        "p_cookies_titulo": "6. Cookies and Session Data",
        "p_cookies_texto": "Our follow-up portal uses a technical session cookie required for the page to work properly. We do not use advertising tracking cookies.",
        "p_cambios_titulo": "7. Changes to This Policy",
        "p_cambios_texto": "We may update this policy from time to time. The current version's date will always be available on this same page.",
        "p_seguridad_titulo": "Security Measures",
        "p_seguridad_texto": "Your information is transmitted over an encrypted connection (HTTPS) and stored in a database with access controls. Our staff passwords are stored encrypted, never in plain text, and access to your data is limited to authorized {nombre} personnel.",
        "p_menores_titulo": "Minors",
        "p_menores_texto": "Our services are intended for adults. We do not knowingly collect data from minors. If we discover that a minor provided data without parental or guardian consent, we will delete it.",
        "p_minimizacion_titulo": "Data Minimization",
        "p_minimizacion_texto": "We only request the data strictly necessary to follow up on your property search. We do not ask for sensitive information (health, religion, sexual orientation, etc.) and ask that you avoid including such details in the message field.",
        "p_brecha_titulo": "Security Incident Notification",
        "p_brecha_texto": "In the event of a security breach affecting your personal data, we commit to notifying you and the relevant authority within the timeframes required by applicable law.",
        "p_ejercicio_titulo": "How to Exercise Your Rights",
        "p_ejercicio_texto": "To exercise any of your rights, contact us using the details at the end of this page, clearly stating your request. We will respond {plazo}.",
        "p_contacto_label": "📩 Questions about your data? Contact {nombre} directly",
        "p_whatsapp_txt": "via WhatsApp at",
        "p_correo_txt": "or by email at",
        "t_titulo": "📋 Terms of Use",
        "t_subtitulo": "conditions for using our contact form and follow-up portal",
        "t_intro": "By filling out our contact form or using our follow-up portal, you agree to the following terms.",
        "t_secciones": [
            ("1. About This Service", "{nombre} provides a contact form and a follow-up portal to facilitate your property search and communication with our team of advisors."),
            ("2. Appropriate Use", "You agree to provide truthful and up-to-date information when filling out our form. We reserve the right not to follow up on requests with false or incomplete information."),
            ("3. No Availability Guarantee", "Properties shown on our portal are subject to availability and may change without notice. We do not guarantee that a property you are interested in will still be available when we contact you."),
            ("4. Communication", "By providing your phone number and/or email, you authorize our team to contact you through those channels (including WhatsApp and email) to follow up on your request."),
            ("5. Scheduled Visits", "If you schedule a visit through our portal, you agree to confirm or reschedule in advance if you cannot attend, so as not to affect our advisors' availability."),
            ("6. Content Ownership", "The content, photos, and descriptions of published properties are the property of {nombre} and may not be reproduced without authorization."),
            ("7. Changes to These Terms", "We may update these terms from time to time. The current version will always be available on this same page."),
        ],
        "t_contacto_label": "📩 Questions about these terms? Contact {nombre} directly",
        "selector_titulo": "Select your country or region",
        "selector_sub": "The legal content changes based on the data protection framework that applies to you.",
    },
    "fr": {
        "lang_attr": "fr",
        "volver": "← Retour",
        "p_titulo": "🔒 Politique de Confidentialité",
        "p_subtitulo": "données personnelles que nous collectons et comment nous les utilisons",
        "p_intro": "Cette politique explique quelles informations personnelles {nombre} collecte lorsque vous remplissez notre formulaire de contact, et comment nous les utilisons pour mieux vous servir.",
        "p_resp_titulo": "1. Responsable du traitement",
        "p_resp_texto": "{nombre} est responsable des données personnelles que vous partagez via notre formulaire de contact et notre portail de suivi.",
        "p_datos_titulo": "2. Données que nous collectons",
        "p_datos_intro": "Lorsque vous remplissez notre formulaire, nous collectons :",
        "p_datos_lista": ["Nom complet", "Numéro de téléphone", "Adresse e-mail (si fournie)", "Zone d'intérêt et budget approximatif", "Tout message supplémentaire que vous nous envoyez"],
        "p_finalidad_titulo": "3. Comment nous utilisons vos données",
        "p_finalidad_lista": ["Vous contacter pour assurer le suivi de votre recherche immobilière", "Vous recommander des propriétés correspondant à votre recherche", "Coordonner et vous rappeler les visites de propriétés programmées", "Vous envoyer des mises à jour pertinentes sur votre recherche"],
        "p_comparticion_titulo": "4. Avec qui nous partageons vos données",
        "p_comparticion_texto": "Vos données sont traitées via notre système de gestion interne (CRM) à usage exclusif de notre équipe commerciale. Nous ne vendons pas vos informations à des tiers à des fins de marketing sans rapport avec notre relation commerciale. Nous pouvons utiliser des outils d'e-mail et WhatsApp pour communiquer directement avec vous.",
        "p_conservacion_titulo": "5. Durée de conservation de vos données",
        "p_conservacion_texto": "Nous conservons vos informations tant qu'une relation commerciale active ou potentielle existe, ou jusqu'à ce que vous demandiez leur suppression.",
        "p_cookies_titulo": "6. Cookies et session",
        "p_cookies_texto": "Notre portail de suivi utilise un cookie de session technique nécessaire au bon fonctionnement de la page. Nous n'utilisons pas de cookies de suivi publicitaire.",
        "p_cambios_titulo": "7. Modifications de cette politique",
        "p_cambios_texto": "Nous pouvons mettre à jour cette politique occasionnellement. La date de la version en vigueur sera toujours disponible sur cette même page.",
        "p_seguridad_titulo": "Mesures de sécurité",
        "p_seguridad_texto": "Vos informations sont transmises via une connexion chiffrée (HTTPS) et stockées dans une base de données avec contrôles d'accès. Les mots de passe de notre personnel sont stockés chiffrés, jamais en texte clair, et l'accès à vos données est limité au personnel autorisé de {nombre}.",
        "p_menores_titulo": "Mineurs",
        "p_menores_texto": "Nos services s'adressent aux personnes majeures. Nous ne collectons pas sciemment de données de mineurs. Si nous découvrons qu'un mineur nous a fourni des données sans consentement parental, nous les supprimerons.",
        "p_minimizacion_titulo": "Minimisation des données",
        "p_minimizacion_texto": "Nous ne demandons que les données strictement nécessaires au suivi de votre recherche immobilière. Nous ne demandons pas d'informations sensibles (santé, religion, orientation sexuelle, etc.) et vous demandons d'éviter d'inclure ce type de données dans le champ message.",
        "p_brecha_titulo": "Notification des incidents de sécurité",
        "p_brecha_texto": "En cas de violation de données affectant vos données personnelles, nous nous engageons à vous en informer ainsi que l'autorité compétente dans les délais requis par la loi applicable.",
        "p_ejercicio_titulo": "Comment exercer vos droits",
        "p_ejercicio_texto": "Pour exercer l'un de vos droits, contactez-nous via les coordonnées en bas de cette page, en précisant clairement votre demande. Nous vous répondrons {plazo}.",
        "p_contacto_label": "📩 Questions sur vos données ? Contactez {nombre} directement",
        "p_whatsapp_txt": "par WhatsApp au",
        "p_correo_txt": "ou par e-mail à",
        "t_titulo": "📋 Conditions d'Utilisation",
        "t_subtitulo": "conditions d'utilisation de notre formulaire et portail de suivi",
        "t_intro": "En remplissant notre formulaire de contact ou en utilisant notre portail de suivi, vous acceptez les conditions suivantes.",
        "t_secciones": [
            ("1. À propos de ce service", "{nombre} met à votre disposition un formulaire de contact et un portail de suivi pour faciliter votre recherche immobilière et la communication avec notre équipe de conseillers."),
            ("2. Utilisation appropriée", "Vous vous engagez à fournir des informations véridiques et à jour lorsque vous remplissez notre formulaire. Nous nous réservons le droit de ne pas donner suite aux demandes contenant des informations fausses ou incomplètes."),
            ("3. Aucune garantie de disponibilité", "Les propriétés présentées sur notre portail sont sujettes à disponibilité et peuvent changer sans préavis. Nous ne garantissons pas qu'une propriété qui vous intéresse restera disponible au moment où nous vous contacterons."),
            ("4. Communication", "En nous fournissant votre téléphone et/ou e-mail, vous autorisez notre équipe à vous contacter par ces moyens (y compris WhatsApp et e-mail) pour assurer le suivi de votre demande."),
            ("5. Visites programmées", "Si vous programmez une visite via notre portail, vous vous engagez à confirmer ou reprogrammer à l'avance si vous ne pouvez pas y assister, afin de ne pas affecter la disponibilité de nos conseillers."),
            ("6. Propriété du contenu", "Le contenu, les photos et les descriptions des propriétés publiées sont la propriété de {nombre} et ne peuvent être reproduits sans autorisation."),
            ("7. Modifications de ces conditions", "Nous pouvons mettre à jour ces conditions occasionnellement. La version en vigueur sera toujours disponible sur cette même page."),
        ],
        "t_contacto_label": "📩 Questions sur ces conditions ? Contactez {nombre} directement",
        "selector_titulo": "Sélectionnez votre pays ou région",
        "selector_sub": "Le contenu juridique change selon le cadre de protection des données qui vous est applicable.",
    },
    "de": {
        "lang_attr": "de",
        "volver": "← Zurück",
        "p_titulo": "🔒 Datenschutzerklärung",
        "p_subtitulo": "personenbezogene Daten, die wir erheben, und wie wir sie verwenden",
        "p_intro": "Diese Erklärung beschreibt, welche personenbezogenen Daten {nombre} erhebt, wenn Sie unser Kontaktformular ausfüllen, und wie wir diese verwenden, um Sie besser zu betreuen.",
        "p_resp_titulo": "1. Verantwortlicher",
        "p_resp_texto": "{nombre} ist verantwortlich für die personenbezogenen Daten, die Sie über unser Kontaktformular und unser Nachverfolgungsportal teilen.",
        "p_datos_titulo": "2. Daten, die wir erheben",
        "p_datos_intro": "Beim Ausfüllen unseres Formulars erheben wir:",
        "p_datos_lista": ["Vollständiger Name", "Telefonnummer", "E-Mail-Adresse (falls angegeben)", "Interessengebiet und ungefähres Budget", "Jede zusätzliche Nachricht, die Sie uns senden"],
        "p_finalidad_titulo": "3. Wofür wir Ihre Daten verwenden",
        "p_finalidad_lista": ["Um Sie zu kontaktieren und Ihre Immobiliensuche zu begleiten", "Um Ihnen passende Immobilien zu empfehlen", "Um vereinbarte Besichtigungstermine zu koordinieren und zu erinnern", "Um Ihnen relevante Updates zu Ihrer Suche zu senden"],
        "p_comparticion_titulo": "4. Mit wem wir Ihre Daten teilen",
        "p_comparticion_texto": "Ihre Daten werden über unser internes Verwaltungssystem (CRM) ausschließlich von unserem Vertriebsteam verarbeitet. Wir verkaufen Ihre Daten nicht an Dritte für Marketingzwecke außerhalb unserer Geschäftsbeziehung. Wir können E-Mail- und WhatsApp-Tools nutzen, um direkt mit Ihnen zu kommunizieren.",
        "p_conservacion_titulo": "5. Wie lange wir Ihre Daten speichern",
        "p_conservacion_texto": "Wir bewahren Ihre Daten auf, solange eine aktive oder potenzielle Geschäftsbeziehung besteht, oder bis Sie deren Löschung beantragen.",
        "p_cookies_titulo": "6. Cookies und Sitzungsdaten",
        "p_cookies_texto": "Unser Nachverfolgungsportal verwendet ein technisch notwendiges Sitzungs-Cookie, damit die Seite ordnungsgemäß funktioniert. Wir verwenden keine Werbe-Tracking-Cookies.",
        "p_cambios_titulo": "7. Änderungen dieser Richtlinie",
        "p_cambios_texto": "Wir können diese Richtlinie gelegentlich aktualisieren. Das Datum der aktuellen Version ist immer auf dieser Seite verfügbar.",
        "p_seguridad_titulo": "Sicherheitsmaßnahmen",
        "p_seguridad_texto": "Ihre Informationen werden über eine verschlüsselte Verbindung (HTTPS) übertragen und in einer Datenbank mit Zugriffskontrollen gespeichert. Die Passwörter unseres Personals werden verschlüsselt gespeichert, niemals im Klartext, und der Zugriff auf Ihre Daten ist auf autorisiertes Personal von {nombre} beschränkt.",
        "p_menores_titulo": "Minderjährige",
        "p_menores_texto": "Unsere Dienste richten sich an Erwachsene. Wir erheben wissentlich keine Daten von Minderjährigen. Sollten wir feststellen, dass ein Minderjähriger uns ohne elterliche Zustimmung Daten übermittelt hat, werden wir diese löschen.",
        "p_minimizacion_titulo": "Datenminimierung",
        "p_minimizacion_texto": "Wir fordern nur die Daten an, die für die Nachverfolgung Ihrer Immobiliensuche unbedingt erforderlich sind. Wir fragen nicht nach sensiblen Informationen (Gesundheit, Religion, sexuelle Orientierung usw.) und bitten Sie, solche Angaben nicht im Nachrichtenfeld zu machen.",
        "p_brecha_titulo": "Meldung von Sicherheitsvorfällen",
        "p_brecha_texto": "Im Falle einer Datenschutzverletzung, die Ihre personenbezogenen Daten betrifft, verpflichten wir uns, Sie und die zuständige Behörde innerhalb der gesetzlich vorgeschriebenen Fristen zu benachrichtigen.",
        "p_ejercicio_titulo": "Wie Sie Ihre Rechte ausüben",
        "p_ejercicio_texto": "Um eines Ihrer Rechte auszuüben, kontaktieren Sie uns über die Kontaktdaten am Ende dieser Seite und geben Sie Ihr Anliegen klar an. Wir werden {plazo} antworten.",
        "p_contacto_label": "📩 Fragen zu Ihren Daten? Kontaktieren Sie {nombre} direkt",
        "p_whatsapp_txt": "per WhatsApp unter",
        "p_correo_txt": "oder per E-Mail an",
        "t_titulo": "📋 Nutzungsbedingungen",
        "t_subtitulo": "Bedingungen für die Nutzung unseres Formulars und Nachverfolgungsportals",
        "t_intro": "Durch das Ausfüllen unseres Kontaktformulars oder die Nutzung unseres Nachverfolgungsportals stimmen Sie den folgenden Bedingungen zu.",
        "t_secciones": [
            ("1. Über diesen Dienst", "{nombre} stellt Ihnen ein Kontaktformular und ein Nachverfolgungsportal zur Verfügung, um Ihre Immobiliensuche und die Kommunikation mit unserem Beraterteam zu erleichtern."),
            ("2. Angemessene Nutzung", "Sie verpflichten sich, beim Ausfüllen unseres Formulars wahrheitsgemäße und aktuelle Informationen anzugeben. Wir behalten uns das Recht vor, Anfragen mit falschen oder unvollständigen Angaben nicht weiterzuverfolgen."),
            ("3. Keine Verfügbarkeitsgarantie", "Die auf unserem Portal gezeigten Immobilien unterliegen der Verfügbarkeit und können sich ohne Vorankündigung ändern. Wir garantieren nicht, dass eine für Sie interessante Immobilie zum Zeitpunkt der Kontaktaufnahme noch verfügbar ist."),
            ("4. Kommunikation", "Durch die Angabe Ihrer Telefonnummer und/oder E-Mail autorisieren Sie unser Team, Sie über diese Kanäle (einschließlich WhatsApp und E-Mail) zu kontaktieren, um Ihre Anfrage zu bearbeiten."),
            ("5. Vereinbarte Besichtigungen", "Wenn Sie über unser Portal einen Besichtigungstermin vereinbaren, verpflichten Sie sich, diesen rechtzeitig zu bestätigen oder zu verschieben, falls Sie nicht teilnehmen können, um die Verfügbarkeit unserer Berater nicht zu beeinträchtigen."),
            ("6. Eigentum am Inhalt", "Die Inhalte, Fotos und Beschreibungen der veröffentlichten Immobilien sind Eigentum von {nombre} und dürfen ohne Genehmigung nicht reproduziert werden."),
            ("7. Änderungen dieser Bedingungen", "Wir können diese Bedingungen gelegentlich aktualisieren. Die aktuelle Version ist immer auf dieser Seite verfügbar."),
        ],
        "t_contacto_label": "📩 Fragen zu diesen Bedingungen? Kontaktieren Sie {nombre} direkt",
        "selector_titulo": "Wählen Sie Ihr Land oder Ihre Region",
        "selector_sub": "Der rechtliche Inhalt ändert sich je nach dem für Sie geltenden Datenschutzrahmen.",
    },
    "pt": {
        "lang_attr": "pt",
        "volver": "← Voltar",
        "p_titulo": "🔒 Política de Privacidade",
        "p_subtitulo": "dados pessoais que coletamos e como os usamos",
        "p_intro": "Esta política explica quais informações pessoais {nombre} coleta quando você preenche nosso formulário de contato, e como as usamos para atendê-lo melhor.",
        "p_resp_titulo": "1. Responsável pelo tratamento",
        "p_resp_texto": "{nombre} é responsável pelos dados pessoais que você compartilha através do nosso formulário de contato e portal de acompanhamento.",
        "p_datos_titulo": "2. Dados que coletamos",
        "p_datos_intro": "Ao preencher nosso formulário, coletamos:",
        "p_datos_lista": ["Nome completo", "Número de telefone", "E-mail (se fornecido)", "Zona de interesse e orçamento aproximado", "Qualquer mensagem adicional que nos enviar"],
        "p_finalidad_titulo": "3. Para que usamos seus dados",
        "p_finalidad_lista": ["Contatá-lo para dar seguimento à sua busca por imóvel", "Recomendar imóveis que correspondam ao que você procura", "Coordenar e lembrá-lo de visitas agendadas a imóveis", "Enviar atualizações relevantes sobre seu processo de busca"],
        "p_comparticion_titulo": "4. Com quem compartilhamos seus dados",
        "p_comparticion_texto": "Seus dados são processados através do nosso sistema de gestão interno (CRM) para uso exclusivo da nossa equipe de vendas. Não vendemos suas informações a terceiros para fins de marketing alheios à nossa relação comercial. Podemos usar ferramentas de e-mail e WhatsApp para nos comunicarmos diretamente com você.",
        "p_conservacion_titulo": "5. Por quanto tempo conservamos seus dados",
        "p_conservacion_texto": "Conservamos suas informações enquanto existir uma relação comercial ativa ou potencial, ou até que você solicite sua exclusão.",
        "p_cookies_titulo": "6. Cookies e sessão",
        "p_cookies_texto": "Nosso portal de acompanhamento usa um cookie de sessão técnico necessário para que a página funcione corretamente. Não usamos cookies de rastreamento publicitário.",
        "p_cambios_titulo": "7. Alterações nesta política",
        "p_cambios_texto": "Podemos atualizar esta política ocasionalmente. A data da versão vigente estará sempre disponível nesta mesma página.",
        "p_seguridad_titulo": "Medidas de segurança",
        "p_seguridad_texto": "Suas informações são transmitidas por conexão criptografada (HTTPS) e armazenadas em um banco de dados com controles de acesso. As senhas da nossa equipe são armazenadas de forma criptografada, nunca em texto simples, e o acesso aos seus dados é limitado à equipe autorizada de {nombre}.",
        "p_menores_titulo": "Menores de idade",
        "p_menores_texto": "Nossos serviços são destinados a maiores de idade. Não coletamos intencionalmente dados de menores. Se descobrirmos que um menor nos forneceu dados sem consentimento dos pais ou responsáveis, iremos excluí-los.",
        "p_minimizacion_titulo": "Minimização de dados",
        "p_minimizacion_texto": "Solicitamos apenas os dados estritamente necessários para dar seguimento à sua busca por imóvel. Não solicitamos informações sensíveis (saúde, religião, orientação sexual, etc.) e pedimos que evite incluir esse tipo de dado no campo de mensagem.",
        "p_brecha_titulo": "Notificação de incidentes de segurança",
        "p_brecha_texto": "Em caso de incidente de segurança que comprometa seus dados pessoais, nos comprometemos a notificá-lo e a notificar a autoridade competente dentro dos prazos exigidos pela lei aplicável.",
        "p_ejercicio_titulo": "Como exercer seus direitos",
        "p_ejercicio_texto": "Para exercer qualquer um dos seus direitos, entre em contato conosco usando os dados no final desta página, indicando claramente sua solicitação. Responderemos {plazo}.",
        "p_contacto_label": "📩 Dúvidas sobre seus dados? Contate {nombre} diretamente",
        "p_whatsapp_txt": "pelo WhatsApp no",
        "p_correo_txt": "ou pelo e-mail",
        "t_titulo": "📋 Termos de Uso",
        "t_subtitulo": "condições para usar nosso formulário e portal de acompanhamento",
        "t_intro": "Ao preencher nosso formulário de contato ou usar nosso portal de acompanhamento, você aceita os seguintes termos.",
        "t_secciones": [
            ("1. Sobre este serviço", "{nombre} disponibiliza um formulário de contato e um portal de acompanhamento para facilitar sua busca por imóveis e a comunicação com nossa equipe de consultores."),
            ("2. Uso adequado", "Você se compromete a fornecer informações verdadeiras e atualizadas ao preencher nosso formulário. Reservamo-nos o direito de não dar seguimento a solicitações com informações falsas ou incompletas."),
            ("3. Sem garantia de disponibilidade", "Os imóveis mostrados em nosso portal estão sujeitos à disponibilidade e podem mudar sem aviso prévio. Não garantimos que um imóvel de seu interesse continuará disponível no momento do contato."),
            ("4. Comunicação", "Ao nos fornecer seu telefone e/ou e-mail, você autoriza nossa equipe a se comunicar com você por esses meios (incluindo WhatsApp e e-mail) para dar seguimento à sua solicitação."),
            ("5. Visitas agendadas", "Se agendar uma visita através do nosso portal, você se compromete a confirmar ou reagendar com antecedência caso não possa comparecer, para não afetar a disponibilidade de nossos consultores."),
            ("6. Propriedade do conteúdo", "O conteúdo, fotos e descrições dos imóveis publicados são propriedade de {nombre} e não podem ser reproduzidos sem autorização."),
            ("7. Alterações a estes termos", "Podemos atualizar estes termos ocasionalmente. A versão vigente estará sempre disponível nesta mesma página."),
        ],
        "t_contacto_label": "📩 Dúvidas sobre estes termos? Contate {nombre} diretamente",
        "selector_titulo": "Selecione seu país ou região",
        "selector_sub": "O conteúdo legal muda conforme o marco de proteção de dados aplicável a você.",
    },
    "zh": {
        "lang_attr": "zh",
        "volver": "← 返回",
        "p_titulo": "🔒 隐私政策",
        "p_subtitulo": "我们收集的个人信息及使用方式",
        "p_intro": "本政策说明当您填写我们的联系表格时，{nombre}会收集哪些个人信息，以及我们如何使用这些信息为您提供更好的服务。",
        "p_resp_titulo": "1. 数据处理责任方",
        "p_resp_texto": "{nombre}负责您通过我们的联系表格和跟进门户分享的个人数据。",
        "p_datos_titulo": "2. 我们收集的数据",
        "p_datos_intro": "填写我们的表格时，我们会收集：",
        "p_datos_lista": ["全名", "电话号码", "电子邮箱（如提供）", "意向区域和大致预算", "您发送给我们的任何附加信息"],
        "p_finalidad_titulo": "3. 我们如何使用您的数据",
        "p_finalidad_lista": ["联系您以跟进您的购房需求", "向您推荐符合您需求的房产", "协调并提醒您已安排的看房时间", "向您发送与您的搜索相关的更新信息"],
        "p_comparticion_titulo": "4. 我们与谁共享您的数据",
        "p_comparticion_texto": "您的数据通过我们内部的管理系统（CRM）处理，仅供我们的销售团队使用。我们不会将您的信息出售给第三方用于与我们业务关系无关的营销目的。我们可能会使用电子邮件和WhatsApp工具直接与您沟通。",
        "p_conservacion_titulo": "5. 我们保留您数据的时长",
        "p_conservacion_texto": "只要存在活跃或潜在的业务关系，我们就会保留您的信息，直到您要求删除为止。",
        "p_cookies_titulo": "6. Cookie和会话",
        "p_cookies_texto": "我们的跟进门户使用技术性会话Cookie，这是页面正常运行所必需的。我们不使用广告追踪Cookie。",
        "p_cambios_titulo": "7. 本政策的变更",
        "p_cambios_texto": "我们可能会不时更新本政策。当前版本的日期将始终在本页面上显示。",
        "p_seguridad_titulo": "安全措施",
        "p_seguridad_texto": "您的信息通过加密连接（HTTPS）传输，并存储在具有访问控制的数据库中。我们员工的密码均加密存储，绝不以明文形式保存，且只有{nombre}的授权人员才能访问您的数据。",
        "p_menores_titulo": "未成年人",
        "p_menores_texto": "我们的服务面向成年人。我们不会故意收集未成年人的数据。如果我们发现未成年人在未经父母或监护人同意的情况下向我们提供了数据，我们将予以删除。",
        "p_minimizacion_titulo": "数据最小化",
        "p_minimizacion_texto": "我们仅收集跟进您房产搜索严格必要的数据。我们不会询问敏感信息（健康、宗教、性取向等），并请您避免在留言栏中包含此类信息。",
        "p_brecha_titulo": "安全事件通知",
        "p_brecha_texto": "如发生影响您个人数据的安全事件，我们承诺按照适用法律要求的时限通知您及相关主管部门。",
        "p_ejercicio_titulo": "如何行使您的权利",
        "p_ejercicio_texto": "如需行使您的任何权利，请使用本页底部的联系方式与我们联系，并清楚说明您的请求。我们将{plazo}回复。",
        "p_contacto_label": "📩 对您的数据有疑问？请直接联系{nombre}",
        "p_whatsapp_txt": "通过WhatsApp联系",
        "p_correo_txt": "或发送邮件至",
        "t_titulo": "📋 使用条款",
        "t_subtitulo": "使用我们表格和跟进门户的条件",
        "t_intro": "填写我们的联系表格或使用我们的跟进门户，即表示您同意以下条款。",
        "t_secciones": [
            ("1. 关于本服务", "{nombre}提供联系表格和跟进门户，以便您搜索房产并与我们的顾问团队沟通。"),
            ("2. 适当使用", "您承诺在填写表格时提供真实和最新的信息。我们保留对包含虚假或不完整信息的请求不予跟进的权利。"),
            ("3. 不保证可用性", "我们门户展示的房产可能随时变化，恕不另行通知。我们不保证您感兴趣的房产在我们联系您时仍然可用。"),
            ("4. 沟通", "通过向我们提供您的电话和/或电子邮件，您授权我们的团队通过这些渠道（包括WhatsApp和电子邮件）与您联系以跟进您的请求。"),
            ("5. 预约看房", "如果您通过我们的门户预约看房，您承诺如无法出席会提前确认或改期，以免影响我们顾问的时间安排。"),
            ("6. 内容所有权", "已发布房产的内容、照片和描述归{nombre}所有，未经授权不得复制。"),
            ("7. 条款变更", "我们可能会不时更新这些条款。当前版本将始终在本页面上显示。"),
        ],
        "t_contacto_label": "📩 对这些条款有疑问？请直接联系{nombre}",
        "selector_titulo": "选择您的国家或地区",
        "selector_sub": "法律内容会根据适用于您的数据保护框架而变化。",
    },
}

# ============================================================
# REGIONES — lo que cambia por país/marco legal
# ============================================================
REGIONES = {
    "us": {
        "idioma": "en", "bandera": "🇺🇸", "nombre_display": "United States",
        "ley_referencia": "California Consumer Privacy Act (CCPA) as amended by the CPRA, and similar state privacy laws (e.g. Virginia CDPA, Colorado CPA)",
        "autoridad": "California Privacy Protection Agency (CPPA), or your state's applicable data protection authority",
        "base_legal": "We process your data based on your consent when submitting the form and our legitimate interest in following up on your inquiry.",
        "derechos_titulo": "Your Rights",
        "derechos_lista": ["Right to know what personal information is collected", "Right to delete personal information we hold about you", "Right to opt out of the sale or sharing of your personal information", "Right to correct inaccurate personal information", "Right to non-discrimination for exercising your privacy rights"],
        "transferencias": "If your data is processed or stored outside your state of residence, we take reasonable steps to protect it consistently with this policy.",
        "nota_juridica": "This policy is written with U.S. state privacy laws in mind (CCPA/CPRA-style rights). Applicable rights may vary depending on your specific state of residence.",
        "plazo_respuesta": "within 45 days, as required by the CCPA/CPRA (extendable by an additional 45 days for complex requests, with notice to you)",
    },
    "es-espana": {
        "idioma": "es", "bandera": "🇪🇸", "nombre_display": "España",
        "ley_referencia": "Reglamento General de Protección de Datos (RGPD/UE 2016/679) y la Ley Orgánica 3/2018 de Protección de Datos Personales y garantía de los derechos digitales (LOPDGDD)",
        "autoridad": "Agencia Española de Protección de Datos (AEPD) — www.aepd.es",
        "base_legal": "Tratamos sus datos con base en su consentimiento expreso al enviar el formulario, y nuestro interés legítimo en darle seguimiento comercial a su solicitud.",
        "derechos_titulo": "Sus derechos (RGPD)",
        "derechos_lista": ["Acceso a sus datos personales", "Rectificación de datos inexactos", "Supresión (\"derecho al olvido\")", "Limitación del tratamiento", "Portabilidad de sus datos", "Oposición al tratamiento", "A no ser objeto de decisiones automatizadas", "A presentar una reclamación ante la AEPD"],
        "transferencias": "Si sus datos se almacenan en servidores fuera del Espacio Económico Europeo, garantizamos que existan las salvaguardas adecuadas conforme al RGPD (como cláusulas contractuales tipo).",
        "nota_juridica": "Esta política está orientada a los requisitos del RGPD y la LOPDGDD aplicables en España.",
        "plazo_respuesta": "en el plazo máximo de un mes conforme al RGPD (prorrogable a tres meses en casos complejos, con aviso previo)",
    },
    "es-latam": {
        "idioma": "es", "bandera": "🌎", "nombre_display": "Otros países de Latinoamérica",
        "ley_referencia": "la ley de protección de datos personales aplicable en su país (por ejemplo, la Ley N.° 29733 en Perú, la Ley N.° 172-12 en República Dominicana, entre otras leyes similares en la región)",
        "autoridad": "la autoridad de protección de datos de su país (varía según la legislación local)",
        "base_legal": "Tratamos sus datos con base en su consentimiento expreso al enviar el formulario, y nuestro interés legítimo en darle seguimiento comercial a su solicitud.",
        "derechos_titulo": "Sus derechos (ARCO)",
        "derechos_lista": ["Acceso a sus datos personales", "Rectificación de datos inexactos o desactualizados", "Cancelación de sus datos cuando ya no sean necesarios", "Oposición al uso de sus datos para fines específicos"],
        "transferencias": None,
        "nota_juridica": "Las leyes de protección de datos varían entre países de Latinoamérica. Esta política usa el marco general de derechos ARCO (Acceso, Rectificación, Cancelación, Oposición), común en la mayoría de las legislaciones de la región, pero le recomendamos verificar la ley específica de su país. Si su país tiene su propia página en este selector (México, Chile, Guatemala, Colombia, Argentina), selecciónela para ver su marco legal exacto.",
        "plazo_respuesta": "en un plazo razonable conforme a la legislación específica de su país",
    },
    "mx": {
        "idioma": "es", "bandera": "🇲🇽", "nombre_display": "México",
        "ley_referencia": "la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP), publicada el 20 de marzo de 2025",
        "autoridad": "la Secretaría Anticorrupción y Buen Gobierno (SABG), que asumió las funciones de protección de datos que antes tenía el INAI (desaparecido por reforma constitucional de diciembre de 2024)",
        "base_legal": "Tratamos sus datos con base en su consentimiento expreso al enviar el formulario, y nuestro interés legítimo en darle seguimiento comercial a su solicitud.",
        "derechos_titulo": "Sus derechos (ARCO)",
        "derechos_lista": ["Acceso a sus datos personales", "Rectificación de datos inexactos o desactualizados", "Cancelación de sus datos cuando ya no sean necesarios", "Oposición al uso de sus datos para fines específicos"],
        "transferencias": None,
        "nota_juridica": "⚠️ El marco institucional mexicano cambió recientemente: el INAI desapareció en 2024-2025 y sus funciones de protección de datos las asumió la Secretaría Anticorrupción y Buen Gobierno bajo una LFPDPPP nueva. Confirme con un abogado local que esta referencia siga vigente al momento de leerla, ya que la implementación de la reforma sigue en marcha.",
        "plazo_respuesta": "en el plazo que establezca la normativa vigente tras la reforma de 2025 (bajo la ley anterior el plazo era de 20 días hábiles)",
    },
    "cl": {
        "idioma": "es", "bandera": "🇨🇱", "nombre_display": "Chile",
        "ley_referencia": "la Ley N.° 21.719, que moderniza la Ley N.° 19.628 y crea la Agencia de Protección de Datos Personales, con entrada en vigor prevista para el 1 de diciembre de 2026",
        "autoridad": "la Agencia de Protección de Datos Personales (APDP)",
        "base_legal": "Tratamos sus datos con base en su consentimiento expreso al enviar el formulario, y nuestro interés legítimo en darle seguimiento comercial a su solicitud.",
        "derechos_titulo": "Sus derechos (ARCO ampliados)",
        "derechos_lista": ["Acceso a sus datos personales", "Rectificación de datos inexactos", "Cancelación/eliminación de sus datos", "Oposición al tratamiento", "Portabilidad de sus datos (nuevo con la Ley 21.719)"],
        "transferencias": None,
        "nota_juridica": "⚠️ La Ley 21.719 es reciente: fue publicada en diciembre de 2024 y su entrada en vigor plena está prevista para el 1 de diciembre de 2026 (existe una discusión legislativa activa sobre postergarla hasta 2027). Confirme con un abogado local el estado vigente de la ley al momento de operar.",
        "plazo_respuesta": "en el plazo que establezca la Ley 21.719 una vez entre en vigor",
    },
    "gt": {
        "idioma": "es", "bandera": "🇬🇹", "nombre_display": "Guatemala",
        "ley_referencia": "actualmente, Guatemala NO cuenta con una ley general de protección de datos personales. La Ley de Acceso a la Información Pública (Decreto 57-2008) regula parcialmente el tratamiento de datos personales, y existe una iniciativa de ley (Iniciativa 4090) pendiente de aprobación en el Congreso",
        "autoridad": "no existe todavía una autoridad especializada en protección de datos personales en Guatemala",
        "base_legal": "Ante la ausencia de una ley específica, tratamos sus datos aplicando como buena práctica voluntaria estándares similares a los derechos ARCO, con base en su consentimiento expreso al enviar el formulario.",
        "derechos_titulo": "Derechos que le reconocemos como buena práctica (ARCO)",
        "derechos_lista": ["Acceso a sus datos personales", "Rectificación de datos inexactos o desactualizados", "Cancelación de sus datos cuando ya no sean necesarios", "Oposición al uso de sus datos para fines específicos"],
        "transferencias": None,
        "nota_juridica": "⚠️ Guatemala aún no tiene una ley integral de protección de datos personales vigente. Le ofrecemos estos derechos como estándar voluntario de buenas prácticas mientras se aprueba la legislación local, no porque la ley lo exija actualmente.",
        "plazo_respuesta": "en un plazo razonable, dado que Guatemala aún no cuenta con un plazo legal establecido para este tipo de solicitudes",
    },
    "co": {
        "idioma": "es", "bandera": "🇨🇴", "nombre_display": "Colombia",
        "ley_referencia": "la Ley Estatutaria 1581 de 2012 y su Decreto reglamentario 1377 de 2013",
        "autoridad": "la Superintendencia de Industria y Comercio (SIC), a través de la Delegatura para la Protección de Datos Personales",
        "base_legal": "Tratamos sus datos con base en su autorización previa, expresa e informada al enviar el formulario, y nuestro interés legítimo en darle seguimiento comercial a su solicitud.",
        "derechos_titulo": "Sus derechos (ARCO)",
        "derechos_lista": ["Conocer, actualizar y rectificar sus datos personales", "Solicitar prueba de la autorización otorgada", "Ser informado sobre el uso de sus datos", "Presentar quejas ante la SIC", "Revocar la autorización y/o solicitar la supresión de sus datos", "Acceder gratuitamente a sus datos personales"],
        "transferencias": None,
        "nota_juridica": "Esta política está orientada a los requisitos de la Ley 1581 de 2012 aplicable en Colombia.",
        "plazo_respuesta": "en un máximo de 10 días hábiles para consultas y 15 días hábiles para reclamos, conforme a la Ley 1581 de 2012",
    },
    "ar": {
        "idioma": "es", "bandera": "🇦🇷", "nombre_display": "Argentina",
        "ley_referencia": "la Ley de Protección de Datos Personales N.° 25.326",
        "autoridad": "la Agencia de Acceso a la Información Pública (AAIP)",
        "base_legal": "Tratamos sus datos con base en su consentimiento expreso al enviar el formulario, y nuestro interés legítimo en darle seguimiento comercial a su solicitud.",
        "derechos_titulo": "Sus derechos (ARCO)",
        "derechos_lista": ["Acceso a sus datos personales", "Rectificación de datos inexactos o desactualizados", "Actualización de sus datos", "Supresión de sus datos cuando corresponda", "Confidencialidad de su información"],
        "transferencias": None,
        "nota_juridica": "Esta política está orientada a los requisitos de la Ley 25.326 aplicable en Argentina, supervisada por la AAIP.",
        "plazo_respuesta": "en un plazo de 10 días hábiles, conforme a la Ley 25.326",
    },
    "eu-fr": {
        "idioma": "fr", "bandera": "🇫🇷", "nombre_display": "France",

        "ley_referencia": "le Règlement Général sur la Protection des Données (RGPD/UE 2016/679) et la Loi Informatique et Libertés",
        "autoridad": "la Commission Nationale de l'Informatique et des Libertés (CNIL) — www.cnil.fr",
        "base_legal": "Nous traitons vos données sur la base de votre consentement exprès lors de l'envoi du formulaire, et de notre intérêt légitime à assurer le suivi commercial de votre demande.",
        "derechos_titulo": "Vos droits (RGPD)",
        "derechos_lista": ["Droit d'accès à vos données personnelles", "Droit de rectification des données inexactes", "Droit à l'effacement (\"droit à l'oubli\")", "Droit à la limitation du traitement", "Droit à la portabilité de vos données", "Droit d'opposition au traitement", "Droit de ne pas faire l'objet d'une décision automatisée", "Droit d'introduire une réclamation auprès de la CNIL"],
        "transferencias": "Si vos données sont stockées sur des serveurs hors de l'Espace Économique Européen, nous veillons à ce que des garanties appropriées soient en place conformément au RGPD (telles que des clauses contractuelles types).",
        "nota_juridica": "Cette politique est orientée vers les exigences du RGPD applicables en France.",
        "plazo_respuesta": "dans un délai d'un mois maximum, conformément au RGPD (prorogeable à trois mois pour les demandes complexes)",
    },
    "eu-de": {
        "idioma": "de", "bandera": "🇩🇪", "nombre_display": "Deutschland",
        "ley_referencia": "die Datenschutz-Grundverordnung (DSGVO/EU 2016/679) und das Bundesdatenschutzgesetz (BDSG)",
        "autoridad": "der Bundesbeauftragte für den Datenschutz und die Informationsfreiheit (BfDI) oder die zuständige Landesdatenschutzbehörde",
        "base_legal": "Wir verarbeiten Ihre Daten auf Grundlage Ihrer ausdrücklichen Einwilligung bei Absenden des Formulars sowie unseres berechtigten Interesses an der geschäftlichen Nachverfolgung Ihrer Anfrage.",
        "derechos_titulo": "Ihre Rechte (DSGVO)",
        "derechos_lista": ["Recht auf Auskunft über Ihre personenbezogenen Daten", "Recht auf Berichtigung unrichtiger Daten", "Recht auf Löschung (\"Recht auf Vergessenwerden\")", "Recht auf Einschränkung der Verarbeitung", "Recht auf Datenübertragbarkeit", "Widerspruchsrecht gegen die Verarbeitung", "Recht, keiner automatisierten Entscheidung unterworfen zu werden", "Recht auf Beschwerde bei der zuständigen Aufsichtsbehörde"],
        "transferencias": "Falls Ihre Daten auf Servern außerhalb des Europäischen Wirtschaftsraums gespeichert werden, stellen wir sicher, dass angemessene Garantien gemäß der DSGVO bestehen (z. B. Standardvertragsklauseln).",
        "nota_juridica": "Diese Richtlinie orientiert sich an den in Deutschland geltenden DSGVO-Anforderungen.",
        "plazo_respuesta": "innerhalb eines Monats gemäß der DSGVO (verlängerbar auf drei Monate bei komplexen Anfragen)",
    },
    "pt-portugal": {
        "idioma": "pt", "bandera": "🇵🇹", "nombre_display": "Portugal",
        "ley_referencia": "o Regulamento Geral sobre a Proteção de Dados (RGPD/UE 2016/679) e a Lei n.º 58/2019",
        "autoridad": "a Comissão Nacional de Proteção de Dados (CNPD) — www.cnpd.pt",
        "base_legal": "Tratamos seus dados com base no seu consentimento expresso ao enviar o formulário, e no nosso interesse legítimo em dar seguimento comercial à sua solicitação.",
        "derechos_titulo": "Os seus direitos (RGPD)",
        "derechos_lista": ["Direito de acesso aos seus dados pessoais", "Direito de retificação de dados inexatos", "Direito ao apagamento (\"direito ao esquecimento\")", "Direito à limitação do tratamento", "Direito à portabilidade dos seus dados", "Direito de oposição ao tratamento", "Direito a não ser sujeito a decisões automatizadas", "Direito de reclamação junto da CNPD"],
        "transferencias": "Caso os seus dados sejam armazenados em servidores fora do Espaço Económico Europeu, garantimos que existem salvaguardas adequadas nos termos do RGPD.",
        "nota_juridica": "Esta política está orientada para os requisitos do RGPD aplicáveis em Portugal.",
        "plazo_respuesta": "no prazo máximo de um mês, nos termos do RGPD (prorrogável até três meses em casos complexos)",
    },
    "pt-brasil": {
        "idioma": "pt", "bandera": "🇧🇷", "nombre_display": "Brasil",
        "ley_referencia": "a Lei Geral de Proteção de Dados Pessoais (LGPD — Lei n.º 13.709/2018)",
        "autoridad": "a Autoridade Nacional de Proteção de Dados (ANPD) — www.gov.br/anpd",
        "base_legal": "Tratamos seus dados com base no seu consentimento expresso ao enviar o formulário, e no nosso legítimo interesse em dar seguimento comercial à sua solicitação, conforme previsto na LGPD.",
        "derechos_titulo": "Os seus direitos (LGPD)",
        "derechos_lista": ["Confirmação da existência de tratamento de dados", "Acesso aos seus dados", "Correção de dados incompletos, inexatos ou desatualizados", "Anonimização, bloqueio ou eliminação de dados desnecessários", "Portabilidade dos dados a outro fornecedor", "Eliminação dos dados tratados com o seu consentimento", "Revogação do consentimento a qualquer momento", "Reclamação junto à ANPD"],
        "transferencias": "Caso seus dados sejam transferidos para fora do Brasil, garantimos que existam salvaguardas adequadas conforme exigido pela LGPD.",
        "nota_juridica": "Esta política está orientada para os requisitos da LGPD aplicáveis no Brasil.",
        "plazo_respuesta": "em prazo razoável, conforme os princípios da LGPD (a ANPD pode fixar prazos específicos por regulamento)",
    },
    "cn": {
        "idioma": "zh", "bandera": "🇨🇳", "nombre_display": "中国",
        "ley_referencia": "《中华人民共和国个人信息保护法》(PIPL)",
        "autoridad": "国家互联网信息办公室 (CAC)",
        "base_legal": "我们根据您提交表格时的明确同意，以及我们在跟进您的咨询方面的合法利益来处理您的数据。",
        "derechos_titulo": "您的权利 (PIPL)",
        "derechos_lista": ["查阅您的个人信息", "复制您的个人信息", "更正或补充不准确的信息", "删除您的个人信息", "撤回您的同意", "要求解释我们的处理规则"],
        "transferencias": "如果您的数据被传输至中国境外，我们将确保按照PIPL的要求采取适当的保护措施（如安全评估或标准合同条款）。",
        "nota_juridica": "本政策参考了中国《个人信息保护法》(PIPL) 的相关要求制定。",
        "plazo_respuesta": "在适用法律规定的合理期限内",
    },
}

# Mapea el idioma del formulario (lo que ya usa el resto de la app) a la
# región legal más probable por defecto. El visitante puede cambiarla.
LANG_TO_REGION_DEFAULT = {
    "es": "es-latam",
    "en": "us",
    "fr": "eu-fr",
    "de": "eu-de",
    "pt": "pt-brasil",
    "zh": "cn",
}
