DICCIONARIO = {
    'es': {
        'titulo_form': 'Por favor, llena tus datos para contactarte.',
        'placeholder_nombre': 'Nombre completo',
        'placeholder_tel': 'Teléfono',
        'placeholder_zona': 'Zona de interés',
        'placeholder_presupuesto': 'Presupuesto USD',
        'placeholder_propiedad': '¿Qué propiedad busca?',
        'boton_enviar': 'Enviar Información',
        'mensaje_exito': '¡Recibido!',
        'subtitulo_exito': 'Nos pondremos en contacto pronto.',
        'login_titulo': 'Acceso Inmobiliaria',
        'login_boton': 'Entrar',
        'historial_titulo': 'Dashboard de Leads',
        'acepto_terminos': 'Acepto el tratamiento de mis datos personales según la política de privacidad.',
        'selecciona_idioma': 'Selecciona tu idioma',
        'col_fecha': 'Fecha',
        'col_clasificacion': 'Clasificación',
        'col_temperatura': 'Prioridad',
        'col_mensaje': 'Mensaje',
        'col_acciones': 'Acciones',
        'col_score': 'Puntuación',
        'btn_descargar': 'Descargar Excel',
        'btn_buscar': 'Buscar por nombre...',
        'btn_limpiar': 'Limpiar',
        'no_leads': 'No hay prospectos.',
        'btn_es': 'Español', 'btn_en': 'English', 'btn_fr': 'Français', 'btn_de': 'Deutsch', 'btn_pt': 'Português', 'btn_zh': '中文',
        'btn_marcar_cliente': 'Cliente',
        'btn_desmarcar': 'Desmarcar',
        'confirm_marcar': '¿Marcar a {nombre} como cliente?',
        'confirm_desmarcar': '¿Desmarcar a {nombre} como cliente?',
        'btn_inventario': '📦 Inventario',
        'btn_herramientas': '🧮 Herramientas',
        'btn_estadisticas': '📈 Estadísticas',
        'btn_cerrar_sesion': '🔒 Cerrar Sesión',
        'msg_cerrar_sesion': 'Por seguridad, recuerda cerrar sesión al terminar',
        'btn_whatsapp': 'Contactar por WhatsApp',
        'btn_ver_propiedades': 'Ver Propiedades Disponibles',
        'pdf_reporte': 'REPORTE DE LEADS',
        'pdf_periodo': 'Período',
        'pdf_fecha': 'Fecha',
        'pdf_col_fecha': 'Fecha', 'pdf_col_nombre': 'Nombre', 'pdf_col_telefono': 'Telefono',
        'pdf_col_zona': 'Zona', 'pdf_col_presupuesto': 'Presupuesto', 'pdf_col_clasificacion': 'Clasificacion',
        'pdf_col_score': 'Score', 'pdf_col_temperatura': 'Temperatura',
        'herr_titulo': 'Herramientas Inmobiliarias',
        'herr_volver': '← Volver',
        'herr_calc1_titulo': '📈 Rentabilidad por Años',
        'herr_precio_inicial': 'Precio Inicial ($)',
        'herr_rentabilidad_anual': '% Rentabilidad Anual',
        'herr_anos_proyectar': 'Años a Proyectar',
        'herr_btn_calc_rentabilidad': 'Calcular Rentabilidad',
        'herr_tabla_anio': 'Año',
        'herr_tabla_valor': 'Valor',
        'herr_tabla_ganancia': 'Ganancia',
        'herr_calc2_titulo': '📐 Precio por Metro Cuadrado',
        'herr_metraje': 'Metraje (m²)',
        'herr_precio_m2': 'Precio por m² ($)',
        'herr_btn_calc_metros': 'Calcular Precio Total',
        'herr_precio_total_label': 'Precio Total de la Propiedad',
        'herr_calc3_titulo': '💰 Calculadora de Enganche',
        'herr_precio_propiedad': 'Precio Total ($)',
        'herr_porcentaje_enganche': '% de Enganche',
        'herr_btn_calc_enganche': 'Calcular Enganche',
        'herr_monto_enganche_label': 'Monto de Enganche',
        'herr_saldo_financiar_label': 'Saldo a Financiar',
        'stats_titulo': 'Estadísticas',
        'stats_volver': '← Volver al Dashboard',
        'stats_periodo_label': 'Período:',
        'stats_periodo_semana': '1 Semana',
        'stats_periodo_mes': '1 Mes',
        'stats_periodo_anio': '1 Año',
        'stats_periodo_todo': 'Todo el tiempo',
        'stats_pdf_semana': 'PDF 1 Semana',
        'stats_pdf_mes': 'PDF 1 Mes',
        'stats_pdf_anio': 'PDF 1 Año',
        'stats_pdf_todo': 'PDF Todo',
        'stats_total_leads': 'Total de Leads',
        'stats_leads_mes': 'Leads Este Mes',
        'stats_tasa_conversion': 'Tasa de Conversión',
        'stats_chart_zona': 'Leads por Zona',
        'stats_chart_clasificacion': 'Leads por Clasificación',
        'inv_titulo_pagina': 'Inventario de Propiedades',
        'inv_btn_agregar': 'Agregar Propiedad',
        'inv_btn_volver': 'Volver',
        'inv_buscar_placeholder': 'Buscar por título o ubicación...',
        'inv_vacio_titulo': 'No hay propiedades aún',
        'inv_vacio_texto': 'Comienza agregando tu primera propiedad',
        'inv_sin_resultados_titulo': 'Sin resultados',
        'inv_sin_resultados_texto': 'No encontramos propiedades con ese criterio',
        'inv_sin_descripcion': 'Sin descripción',
        'inv_btn_ver': 'Ver',
        'inv_btn_editar': 'Editar',
        'inv_confirmar_eliminar': '¿Eliminar esta propiedad?',
        'inv_modal_agregar_titulo': 'Agregar Nueva Propiedad',
        'inv_modal_editar_titulo': 'Editar Propiedad',
        'inv_label_titulo': 'Título *',
        'inv_placeholder_titulo': 'Ej: Casa en Zona 10',
        'inv_label_descripcion': 'Descripción',
        'inv_placeholder_descripcion': 'Detalles de la propiedad...',
        'inv_label_precio': 'Precio (USD) *',
        'inv_label_ubicacion': 'Ubicación *',
        'inv_placeholder_ubicacion': 'Ej: Zona 14, Guatemala',
        'inv_label_habitaciones': 'Habitaciones',
        'inv_label_banos': 'Baños',
        'inv_label_m2': 'm²',
        'inv_label_fotos': 'Fotos (máx. 5)',
        'inv_upload_click': 'Click para subir fotos',
        'inv_upload_sub': 'JPG, PNG, WEBP · Puedes subir varias veces',
        'inv_upload_click_editar': 'Click para agregar más fotos',
        'inv_upload_sub_editar': 'Puedes subir varias veces',
        'inv_btn_guardar': 'Guardar Propiedad',
        'inv_btn_guardar_cambios': 'Guardar Cambios',
        'inv_subiendo_fotos': 'Subiendo fotos...',
        'inv_guardando': 'Guardando...',
        'inv_optimizando': 'Optimizando fotos...',
        'inv_fotos_actuales': 'Fotos actuales',
        'inv_foto_label': 'Foto',
        'inv_sin_fotos': 'Sin fotos aún',
        'inv_info_agrega': 'Las fotos nuevas se agregan a las existentes (máx. 5 en total)',
        'inv_espacio_max': 'Alcanzaste el máximo de 5 fotos',
        'inv_espacio_restante': 'Puedes agregar {n} foto(s) más',
        'inv_alert_max': 'Ya tienes el máximo de 5 fotos. Elimina alguna para agregar otra.',
        'inv_alert_parcial': 'Solo se agregaron {n} foto(s). Máximo 5 fotos por propiedad.',
        'inv_detalle_precio': 'Precio',
        'inv_detalle_ubicacion': 'Ubicación',
        'temp_MUY_CALIENTE': '🔥 MUY CALIENTE', 'temp_CALIENTE': '🔥 CALIENTE', 'temp_MEDIO': '🟡 MEDIO', 'temp_FRIO': '❄️ FRÍO',
        'class_💎 VIP / INVERSIONISTA': 'ALTO VALOR 💎',
        'class_🔥 PROSPECTO A': 'PROSPECTO 🟡',
        'class_🟡 SEGUIMIENTO B': 'SEGUIMIENTO ⚪',
        'class_❄️ LEAD FRÍO': 'LEAD FRÍO ❄️',
        'class_❄️ LEAD FRIO': 'LEAD FRÍO ❄️',
        'class_💎 CLIENTE': 'CLIENTE 💎',
    },
    'en': {
        'titulo_form': 'Please fill in your details to contact you.',
        'placeholder_nombre': 'Full Name',
        'placeholder_tel': 'Phone Number',
        'placeholder_zona': 'Area of interest',
        'placeholder_presupuesto': 'Budget USD',
        'placeholder_propiedad': 'What property are you looking for?',
        'boton_enviar': 'Send Information',
        'mensaje_exito': 'Received!',
        'subtitulo_exito': 'We will contact you soon.',
        'login_titulo': 'Real Estate Access',
        'login_boton': 'Login',
        'historial_titulo': 'Leads Dashboard',
        'acepto_terminos': 'I accept the processing of my personal data.',
        'selecciona_idioma': 'Select your language',
        'col_fecha': 'Date',
        'col_clasificacion': 'Classification',
        'col_temperatura': 'Priority',
        'col_mensaje': 'Message',
        'col_acciones': 'Actions',
        'col_score': 'Score',
        'btn_descargar': 'Download Excel',
        'btn_buscar': 'Search by name...',
        'btn_limpiar': 'Clear',
        'no_leads': 'No leads found.',
        'btn_es': 'Spanish', 'btn_en': 'English', 'btn_fr': 'French', 'btn_de': 'German', 'btn_pt': 'Portuguese', 'btn_zh': 'Chinese',
        'btn_marcar_cliente': 'Client',
        'btn_desmarcar': 'Unmark',
        'confirm_marcar': 'Mark {nombre} as a client?',
        'confirm_desmarcar': 'Unmark {nombre} as a client?',
        'btn_inventario': '📦 Inventory',
        'btn_herramientas': '🧮 Tools',
        'btn_estadisticas': '📈 Statistics',
        'btn_cerrar_sesion': '🔒 Log Out',
        'msg_cerrar_sesion': 'For security, remember to log out when finished',
        'btn_whatsapp': 'Contact via WhatsApp',
        'btn_ver_propiedades': 'View Available Properties',
        'pdf_reporte': 'LEADS REPORT',
        'pdf_periodo': 'Period',
        'pdf_fecha': 'Date',
        'pdf_col_fecha': 'Date', 'pdf_col_nombre': 'Name', 'pdf_col_telefono': 'Phone',
        'pdf_col_zona': 'Zone', 'pdf_col_presupuesto': 'Budget', 'pdf_col_clasificacion': 'Classification',
        'pdf_col_score': 'Score', 'pdf_col_temperatura': 'Temperature',
        'herr_titulo': 'Real Estate Tools',
        'herr_volver': '← Back',
        'herr_calc1_titulo': '📈 Return Over Years',
        'herr_precio_inicial': 'Initial Price ($)',
        'herr_rentabilidad_anual': 'Annual Return %',
        'herr_anos_proyectar': 'Years to Project',
        'herr_btn_calc_rentabilidad': 'Calculate Return',
        'herr_tabla_anio': 'Year',
        'herr_tabla_valor': 'Value',
        'herr_tabla_ganancia': 'Profit',
        'herr_calc2_titulo': '📐 Price per Square Meter',
        'herr_metraje': 'Area (m²)',
        'herr_precio_m2': 'Price per m² ($)',
        'herr_btn_calc_metros': 'Calculate Total Price',
        'herr_precio_total_label': 'Total Property Price',
        'herr_calc3_titulo': '💰 Down Payment Calculator',
        'herr_precio_propiedad': 'Total Price ($)',
        'herr_porcentaje_enganche': 'Down Payment %',
        'herr_btn_calc_enganche': 'Calculate Down Payment',
        'herr_monto_enganche_label': 'Down Payment Amount',
        'herr_saldo_financiar_label': 'Balance to Finance',
        'stats_titulo': 'Statistics',
        'stats_volver': '← Back to Dashboard',
        'stats_periodo_label': 'Period:',
        'stats_periodo_semana': '1 Week',
        'stats_periodo_mes': '1 Month',
        'stats_periodo_anio': '1 Year',
        'stats_periodo_todo': 'All time',
        'stats_pdf_semana': 'PDF 1 Week',
        'stats_pdf_mes': 'PDF 1 Month',
        'stats_pdf_anio': 'PDF 1 Year',
        'stats_pdf_todo': 'PDF All',
        'stats_total_leads': 'Total Leads',
        'stats_leads_mes': 'Leads This Month',
        'stats_tasa_conversion': 'Conversion Rate',
        'stats_chart_zona': 'Leads by Zone',
        'stats_chart_clasificacion': 'Leads by Classification',
        'inv_titulo_pagina': 'Property Inventory',
        'inv_btn_agregar': 'Add Property',
        'inv_btn_volver': 'Back',
        'inv_buscar_placeholder': 'Search by title or location...',
        'inv_vacio_titulo': 'No properties yet',
        'inv_vacio_texto': 'Start by adding your first property',
        'inv_sin_resultados_titulo': 'No results',
        'inv_sin_resultados_texto': "We couldn't find properties matching that",
        'inv_sin_descripcion': 'No description',
        'inv_btn_ver': 'View',
        'inv_btn_editar': 'Edit',
        'inv_confirmar_eliminar': 'Delete this property?',
        'inv_modal_agregar_titulo': 'Add New Property',
        'inv_modal_editar_titulo': 'Edit Property',
        'inv_label_titulo': 'Title *',
        'inv_placeholder_titulo': 'E.g.: House in Zone 10',
        'inv_label_descripcion': 'Description',
        'inv_placeholder_descripcion': 'Property details...',
        'inv_label_precio': 'Price (USD) *',
        'inv_label_ubicacion': 'Location *',
        'inv_placeholder_ubicacion': 'E.g.: Zone 14, Guatemala',
        'inv_label_habitaciones': 'Bedrooms',
        'inv_label_banos': 'Bathrooms',
        'inv_label_m2': 'm²',
        'inv_label_fotos': 'Photos (max. 5)',
        'inv_upload_click': 'Click to upload photos',
        'inv_upload_sub': 'JPG, PNG, WEBP · You can upload several times',
        'inv_upload_click_editar': 'Click to add more photos',
        'inv_upload_sub_editar': 'You can upload several times',
        'inv_btn_guardar': 'Save Property',
        'inv_btn_guardar_cambios': 'Save Changes',
        'inv_subiendo_fotos': 'Uploading photos...',
        'inv_guardando': 'Saving...',
        'inv_optimizando': 'Optimizing photos...',
        'inv_fotos_actuales': 'Current photos',
        'inv_foto_label': 'Photo',
        'inv_sin_fotos': 'No photos yet',
        'inv_info_agrega': 'New photos will be added to the existing ones (max. 5 total)',
        'inv_espacio_max': 'You reached the maximum of 5 photos',
        'inv_espacio_restante': 'You can add {n} more photo(s)',
        'inv_alert_max': 'You already have the maximum of 5 photos. Remove one to add another.',
        'inv_alert_parcial': 'Only {n} photo(s) were added. Maximum 5 photos per property.',
        'inv_detalle_precio': 'Price',
        'inv_detalle_ubicacion': 'Location',
        'temp_MUY_CALIENTE': '🔥 VERY HOT', 'temp_CALIENTE': '🔥 HOT', 'temp_MEDIO': '🟡 MEDIUM', 'temp_FRIO': '❄️ COLD',
        'class_💎 VIP / INVERSIONISTA': 'HIGH VALUE 💎',
        'class_🔥 PROSPECTO A': 'PROSPECT 🟡',
        'class_🟡 SEGUIMIENTO B': 'FOLLOW-UP ⚪',
        'class_❄️ LEAD FRÍO': 'COLD LEAD ❄️',
        'class_❄️ LEAD FRIO': 'COLD LEAD ❄️',
        'class_💎 CLIENTE': 'CLIENT 💎',
    },
    'fr': {
        'titulo_form': 'Veuillez remplir vos coordonnées.',
        'placeholder_nombre': 'Nom complet',
        'placeholder_tel': 'Téléphone',
        'placeholder_zona': "Zone d'intérêt",
        'placeholder_presupuesto': 'Budget USD',
        'placeholder_propiedad': 'Quelle propriété recherchez-vous?',
        'boton_enviar': 'Envoyer les informations',
        'mensaje_exito': 'Reçu!',
        'subtitulo_exito': 'Nous vous contacterons bientôt.',
        'login_titulo': 'Accès Immobilier',
        'login_boton': 'Connexion',
        'historial_titulo': 'Tableau de bord',
        'acepto_terminos': "J'accepte le traitement de mes données.",
        'selecciona_idioma': 'Choisissez votre langue',
        'col_fecha': 'Date',
        'col_clasificacion': 'Classification',
        'col_temperatura': 'Priorité',
        'col_mensaje': 'Message',
        'col_acciones': 'Actions',
        'col_score': 'Score',
        'btn_descargar': 'Télécharger Excel',
        'btn_buscar': 'Chercher par nom...',
        'btn_limpiar': 'Effacer',
        'no_leads': 'Aucun prospect.',
        'btn_es': 'Espagnol', 'btn_en': 'Anglais', 'btn_fr': 'Français', 'btn_de': 'Allemand', 'btn_pt': 'Portugais', 'btn_zh': 'Chinois',
        'btn_marcar_cliente': 'Client',
        'btn_desmarcar': 'Retirer',
        'confirm_marcar': 'Marquer {nombre} comme client ?',
        'confirm_desmarcar': 'Retirer {nombre} en tant que client ?',
        'btn_inventario': '📦 Inventaire',
        'btn_herramientas': '🧮 Outils',
        'btn_estadisticas': '📈 Statistiques',
        'btn_cerrar_sesion': '🔒 Déconnexion',
        'msg_cerrar_sesion': 'Pour votre sécurité, pensez à vous déconnecter',
        'btn_whatsapp': 'Contacter par WhatsApp',
        'btn_ver_propiedades': 'Voir les Propriétés Disponibles',
        'pdf_reporte': 'RAPPORT DE PROSPECTS',
        'pdf_periodo': 'Période',
        'pdf_fecha': 'Date',
        'pdf_col_fecha': 'Date', 'pdf_col_nombre': 'Nom', 'pdf_col_telefono': 'Téléphone',
        'pdf_col_zona': 'Zone', 'pdf_col_presupuesto': 'Budget', 'pdf_col_clasificacion': 'Classification',
        'pdf_col_score': 'Score', 'pdf_col_temperatura': 'Priorité',
        'herr_titulo': 'Outils Immobiliers',
        'herr_volver': '← Retour',
        'herr_calc1_titulo': '📈 Rentabilité sur Plusieurs Années',
        'herr_precio_inicial': 'Prix Initial ($)',
        'herr_rentabilidad_anual': '% Rentabilité Annuelle',
        'herr_anos_proyectar': 'Années à Projeter',
        'herr_btn_calc_rentabilidad': 'Calculer la Rentabilité',
        'herr_tabla_anio': 'Année',
        'herr_tabla_valor': 'Valeur',
        'herr_tabla_ganancia': 'Gain',
        'herr_calc2_titulo': '📐 Prix par Mètre Carré',
        'herr_metraje': 'Superficie (m²)',
        'herr_precio_m2': 'Prix par m² ($)',
        'herr_btn_calc_metros': 'Calculer le Prix Total',
        'herr_precio_total_label': 'Prix Total de la Propriété',
        'herr_calc3_titulo': "💰 Calculateur d'Apport",
        'herr_precio_propiedad': 'Prix Total ($)',
        'herr_porcentaje_enganche': "% d'Apport",
        'herr_btn_calc_enganche': "Calculer l'Apport",
        'herr_monto_enganche_label': "Montant de l'Apport",
        'herr_saldo_financiar_label': 'Solde à Financer',
        'stats_titulo': 'Statistiques',
        'stats_volver': '← Retour au Tableau de bord',
        'stats_periodo_label': 'Période :',
        'stats_periodo_semana': '1 Semaine',
        'stats_periodo_mes': '1 Mois',
        'stats_periodo_anio': '1 An',
        'stats_periodo_todo': 'Tout le temps',
        'stats_pdf_semana': 'PDF 1 Semaine',
        'stats_pdf_mes': 'PDF 1 Mois',
        'stats_pdf_anio': 'PDF 1 An',
        'stats_pdf_todo': 'PDF Tout',
        'stats_total_leads': 'Total des Prospects',
        'stats_leads_mes': 'Prospects ce Mois',
        'stats_tasa_conversion': 'Taux de Conversion',
        'stats_chart_zona': 'Prospects par Zone',
        'stats_chart_clasificacion': 'Prospects par Classification',
        'inv_titulo_pagina': 'Inventaire des Propriétés',
        'inv_btn_agregar': 'Ajouter une Propriété',
        'inv_btn_volver': 'Retour',
        'inv_buscar_placeholder': 'Rechercher par titre ou emplacement...',
        'inv_vacio_titulo': 'Aucune propriété pour le moment',
        'inv_vacio_texto': 'Commencez par ajouter votre première propriété',
        'inv_sin_resultados_titulo': 'Aucun résultat',
        'inv_sin_resultados_texto': 'Aucune propriété ne correspond à ce critère',
        'inv_sin_descripcion': 'Aucune description',
        'inv_btn_ver': 'Voir',
        'inv_btn_editar': 'Modifier',
        'inv_confirmar_eliminar': 'Supprimer cette propriété ?',
        'inv_modal_agregar_titulo': 'Ajouter une Nouvelle Propriété',
        'inv_modal_editar_titulo': 'Modifier la Propriété',
        'inv_label_titulo': 'Titre *',
        'inv_placeholder_titulo': 'Ex : Maison Zone 10',
        'inv_label_descripcion': 'Description',
        'inv_placeholder_descripcion': 'Détails de la propriété...',
        'inv_label_precio': 'Prix (USD) *',
        'inv_label_ubicacion': 'Emplacement *',
        'inv_placeholder_ubicacion': 'Ex : Zone 14, Guatemala',
        'inv_label_habitaciones': 'Chambres',
        'inv_label_banos': 'Salles de bain',
        'inv_label_m2': 'm²',
        'inv_label_fotos': 'Photos (max. 5)',
        'inv_upload_click': 'Cliquez pour ajouter des photos',
        'inv_upload_sub': 'JPG, PNG, WEBP · Vous pouvez en ajouter plusieurs fois',
        'inv_upload_click_editar': 'Cliquez pour ajouter plus de photos',
        'inv_upload_sub_editar': 'Vous pouvez en ajouter plusieurs fois',
        'inv_btn_guardar': 'Enregistrer la Propriété',
        'inv_btn_guardar_cambios': 'Enregistrer les Modifications',
        'inv_subiendo_fotos': 'Téléchargement des photos...',
        'inv_guardando': 'Enregistrement...',
        'inv_optimizando': 'Optimisation des photos...',
        'inv_fotos_actuales': 'Photos actuelles',
        'inv_foto_label': 'Photo',
        'inv_sin_fotos': 'Aucune photo pour le moment',
        'inv_info_agrega': "Les nouvelles photos s'ajouteront aux existantes (max. 5 au total)",
        'inv_espacio_max': 'Vous avez atteint le maximum de 5 photos',
        'inv_espacio_restante': 'Vous pouvez ajouter {n} photo(s) de plus',
        'inv_alert_max': 'Vous avez déjà le maximum de 5 photos. Supprimez-en une pour en ajouter une autre.',
        'inv_alert_parcial': 'Seulement {n} photo(s) ont été ajoutées. Maximum 5 photos par propriété.',
        'inv_detalle_precio': 'Prix',
        'inv_detalle_ubicacion': 'Emplacement',
        'temp_MUY_CALIENTE': '🔥 TRÈS CHAUD', 'temp_CALIENTE': '🔥 CHAUD', 'temp_MEDIO': '🟡 MOYEN', 'temp_FRIO': '❄️ FROID',
        'class_💎 VIP / INVERSIONISTA': 'HAUTE VALEUR 💎',
        'class_🔥 PROSPECTO A': 'PROSPECT 🟡',
        'class_🟡 SEGUIMIENTO B': 'SUIVI ⚪',
        'class_❄️ LEAD FRÍO': 'PROSPECT FROID ❄️',
        'class_❄️ LEAD FRIO': 'PROSPECT FROID ❄️',
        'class_💎 CLIENTE': 'CLIENT 💎',
    },
    'de': {
        'titulo_form': 'Bitte füllen Sie Ihre Daten aus.',
        'placeholder_nombre': 'Vollständiger Name',
        'placeholder_tel': 'Telefonnummer',
        'placeholder_zona': 'Interessengebiet',
        'placeholder_presupuesto': 'Budget USD',
        'placeholder_propiedad': 'Welche Immobilie suchen Sie?',
        'boton_enviar': 'Infos Senden',
        'mensaje_exito': 'Empfangen!',
        'subtitulo_exito': 'Wir melden uns bald.',
        'login_titulo': 'Immobilien Zugang',
        'login_boton': 'Anmelden',
        'historial_titulo': 'Leads Dashboard',
        'acepto_terminos': 'Ich akzeptiere die Datenverarbeitung.',
        'selecciona_idioma': 'Wählen Sie Ihre Sprache',
        'col_fecha': 'Datum',
        'col_clasificacion': 'Klassifizierung',
        'col_temperatura': 'Priorität',
        'col_mensaje': 'Nachricht',
        'col_acciones': 'Aktionen',
        'col_score': 'Punktzahl',
        'btn_descargar': 'Excel Herunterladen',
        'btn_buscar': 'Suchen...',
        'btn_limpiar': 'Löschen',
        'no_leads': 'Keine Leads.',
        'btn_es': 'Spanisch', 'btn_en': 'Englisch', 'btn_fr': 'Französisch', 'btn_de': 'Deutsch', 'btn_pt': 'Portugiesisch', 'btn_zh': 'Chinesisch',
        'btn_marcar_cliente': 'Kunde',
        'btn_desmarcar': 'Entfernen',
        'confirm_marcar': '{nombre} als Kunde markieren?',
        'confirm_desmarcar': '{nombre} als Kunde entfernen?',
        'btn_inventario': '📦 Bestand',
        'btn_herramientas': '🧮 Tools',
        'btn_estadisticas': '📈 Statistiken',
        'btn_cerrar_sesion': '🔒 Abmelden',
        'msg_cerrar_sesion': 'Bitte melden Sie sich nach der Nutzung ab',
        'btn_whatsapp': 'Per WhatsApp kontaktieren',
        'btn_ver_propiedades': 'Verfügbare Immobilien ansehen',
        'pdf_reporte': 'LEADS-BERICHT',
        'pdf_periodo': 'Zeitraum',
        'pdf_fecha': 'Datum',
        'pdf_col_fecha': 'Datum', 'pdf_col_nombre': 'Name', 'pdf_col_telefono': 'Telefon',
        'pdf_col_zona': 'Zone', 'pdf_col_presupuesto': 'Budget', 'pdf_col_clasificacion': 'Klassifizierung',
        'pdf_col_score': 'Punktzahl', 'pdf_col_temperatura': 'Priorität',
        'herr_titulo': 'Immobilien-Tools',
        'herr_volver': '← Zurück',
        'herr_calc1_titulo': '📈 Rendite über die Jahre',
        'herr_precio_inicial': 'Anfangspreis ($)',
        'herr_rentabilidad_anual': '% Jährliche Rendite',
        'herr_anos_proyectar': 'Jahre zur Projektion',
        'herr_btn_calc_rentabilidad': 'Rendite Berechnen',
        'herr_tabla_anio': 'Jahr',
        'herr_tabla_valor': 'Wert',
        'herr_tabla_ganancia': 'Gewinn',
        'herr_calc2_titulo': '📐 Preis pro Quadratmeter',
        'herr_metraje': 'Fläche (m²)',
        'herr_precio_m2': 'Preis pro m² ($)',
        'herr_btn_calc_metros': 'Gesamtpreis Berechnen',
        'herr_precio_total_label': 'Gesamtpreis der Immobilie',
        'herr_calc3_titulo': '💰 Anzahlungsrechner',
        'herr_precio_propiedad': 'Gesamtpreis ($)',
        'herr_porcentaje_enganche': '% Anzahlung',
        'herr_btn_calc_enganche': 'Anzahlung Berechnen',
        'herr_monto_enganche_label': 'Anzahlungsbetrag',
        'herr_saldo_financiar_label': 'Zu Finanzierender Restbetrag',
        'stats_titulo': 'Statistiken',
        'stats_volver': '← Zurück zum Dashboard',
        'stats_periodo_label': 'Zeitraum:',
        'stats_periodo_semana': '1 Woche',
        'stats_periodo_mes': '1 Monat',
        'stats_periodo_anio': '1 Jahr',
        'stats_periodo_todo': 'Gesamte Zeit',
        'stats_pdf_semana': 'PDF 1 Woche',
        'stats_pdf_mes': 'PDF 1 Monat',
        'stats_pdf_anio': 'PDF 1 Jahr',
        'stats_pdf_todo': 'PDF Alles',
        'stats_total_leads': 'Leads Insgesamt',
        'stats_leads_mes': 'Leads Diesen Monat',
        'stats_tasa_conversion': 'Konversionsrate',
        'stats_chart_zona': 'Leads nach Zone',
        'stats_chart_clasificacion': 'Leads nach Klassifizierung',
        'inv_titulo_pagina': 'Immobilienbestand',
        'inv_btn_agregar': 'Immobilie Hinzufügen',
        'inv_btn_volver': 'Zurück',
        'inv_buscar_placeholder': 'Nach Titel oder Standort suchen...',
        'inv_vacio_titulo': 'Noch keine Immobilien',
        'inv_vacio_texto': 'Fügen Sie Ihre erste Immobilie hinzu',
        'inv_sin_resultados_titulo': 'Keine Ergebnisse',
        'inv_sin_resultados_texto': 'Wir konnten keine passenden Immobilien finden',
        'inv_sin_descripcion': 'Keine Beschreibung',
        'inv_btn_ver': 'Ansehen',
        'inv_btn_editar': 'Bearbeiten',
        'inv_confirmar_eliminar': 'Diese Immobilie löschen?',
        'inv_modal_agregar_titulo': 'Neue Immobilie Hinzufügen',
        'inv_modal_editar_titulo': 'Immobilie Bearbeiten',
        'inv_label_titulo': 'Titel *',
        'inv_placeholder_titulo': 'Z.B.: Haus in Zone 10',
        'inv_label_descripcion': 'Beschreibung',
        'inv_placeholder_descripcion': 'Details zur Immobilie...',
        'inv_label_precio': 'Preis (USD) *',
        'inv_label_ubicacion': 'Standort *',
        'inv_placeholder_ubicacion': 'Z.B.: Zone 14, Guatemala',
        'inv_label_habitaciones': 'Schlafzimmer',
        'inv_label_banos': 'Badezimmer',
        'inv_label_m2': 'm²',
        'inv_label_fotos': 'Fotos (max. 5)',
        'inv_upload_click': 'Klicken, um Fotos hochzuladen',
        'inv_upload_sub': 'JPG, PNG, WEBP · Sie können mehrmals hochladen',
        'inv_upload_click_editar': 'Klicken, um weitere Fotos hinzuzufügen',
        'inv_upload_sub_editar': 'Sie können mehrmals hochladen',
        'inv_btn_guardar': 'Immobilie Speichern',
        'inv_btn_guardar_cambios': 'Änderungen Speichern',
        'inv_subiendo_fotos': 'Fotos werden hochgeladen...',
        'inv_guardando': 'Wird gespeichert...',
        'inv_optimizando': 'Fotos werden optimiert...',
        'inv_fotos_actuales': 'Aktuelle Fotos',
        'inv_foto_label': 'Foto',
        'inv_sin_fotos': 'Noch keine Fotos',
        'inv_info_agrega': 'Neue Fotos werden zu den vorhandenen hinzugefügt (max. 5 insgesamt)',
        'inv_espacio_max': 'Sie haben das Maximum von 5 Fotos erreicht',
        'inv_espacio_restante': 'Sie können noch {n} Foto(s) hinzufügen',
        'inv_alert_max': 'Sie haben bereits das Maximum von 5 Fotos. Entfernen Sie eines, um ein weiteres hinzuzufügen.',
        'inv_alert_parcial': 'Nur {n} Foto(s) wurden hinzugefügt. Maximal 5 Fotos pro Immobilie.',
        'inv_detalle_precio': 'Preis',
        'inv_detalle_ubicacion': 'Standort',
        'temp_MUY_CALIENTE': '🔥 SEHR HEISS', 'temp_CALIENTE': '🔥 HEISS', 'temp_MEDIO': '🟡 MITTEL', 'temp_FRIO': '❄️ KALT',
        'class_💎 VIP / INVERSIONISTA': 'HOHER WERT 💎',
        'class_🔥 PROSPECTO A': 'PROSPEKT 🟡',
        'class_🟡 SEGUIMIENTO B': 'NACHVERFOLGUNG ⚪',
        'class_❄️ LEAD FRÍO': 'KALTER LEAD ❄️',
        'class_❄️ LEAD FRIO': 'KALTER LEAD ❄️',
        'class_💎 CLIENTE': 'KUNDE 💎',
    },
    'pt': {
        'titulo_form': 'Preencha seus dados para contato.',
        'placeholder_nombre': 'Nome completo',
        'placeholder_tel': 'Telefone',
        'placeholder_zona': 'Zona de interesse',
        'placeholder_presupuesto': 'Orçamento USD',
        'placeholder_propiedad': 'Que tipo de imóvel procura?',
        'boton_enviar': 'Enviar Informações',
        'mensaje_exito': 'Recebido!',
        'subtitulo_exito': 'Entraremos em contato.',
        'login_titulo': 'Acesso Imobiliário',
        'login_boton': 'Entrar',
        'historial_titulo': 'Painel de Leads',
        'acepto_terminos': 'Aceito o tratamento de dados.',
        'selecciona_idioma': 'Selecione seu idioma',
        'col_fecha': 'Data',
        'col_clasificacion': 'Classificação',
        'col_temperatura': 'Prioridade',
        'col_mensaje': 'Mensagem',
        'col_acciones': 'Ações',
        'col_score': 'Pontuação',
        'btn_descargar': 'Baixar Excel',
        'btn_buscar': 'Buscar...',
        'btn_limpiar': 'Limpar',
        'no_leads': 'Nenhum lead.',
        'btn_es': 'Espanhol', 'btn_en': 'Inglês', 'btn_fr': 'Francês', 'btn_de': 'Alemão', 'btn_pt': 'Português', 'btn_zh': 'Chinês',
        'btn_marcar_cliente': 'Cliente',
        'btn_desmarcar': 'Desmarcar',
        'confirm_marcar': 'Marcar {nombre} como cliente?',
        'confirm_desmarcar': 'Desmarcar {nombre} como cliente?',
        'btn_inventario': '📦 Inventário',
        'btn_herramientas': '🧮 Ferramentas',
        'btn_estadisticas': '📈 Estatísticas',
        'btn_cerrar_sesion': '🔒 Sair',
        'msg_cerrar_sesion': 'Por segurança, lembre-se de sair ao terminar',
        'btn_whatsapp': 'Contatar pelo WhatsApp',
        'btn_ver_propiedades': 'Ver Imóveis Disponíveis',
        'pdf_reporte': 'RELATÓRIO DE LEADS',
        'pdf_periodo': 'Período',
        'pdf_fecha': 'Data',
        'pdf_col_fecha': 'Data', 'pdf_col_nombre': 'Nome', 'pdf_col_telefono': 'Telefone',
        'pdf_col_zona': 'Zona', 'pdf_col_presupuesto': 'Orçamento', 'pdf_col_clasificacion': 'Classificação',
        'pdf_col_score': 'Pontuação', 'pdf_col_temperatura': 'Prioridade',
        'herr_titulo': 'Ferramentas Imobiliárias',
        'herr_volver': '← Voltar',
        'herr_calc1_titulo': '📈 Rentabilidade por Anos',
        'herr_precio_inicial': 'Preço Inicial ($)',
        'herr_rentabilidad_anual': '% Rentabilidade Anual',
        'herr_anos_proyectar': 'Anos a Projetar',
        'herr_btn_calc_rentabilidad': 'Calcular Rentabilidade',
        'herr_tabla_anio': 'Ano',
        'herr_tabla_valor': 'Valor',
        'herr_tabla_ganancia': 'Ganho',
        'herr_calc2_titulo': '📐 Preço por Metro Quadrado',
        'herr_metraje': 'Metragem (m²)',
        'herr_precio_m2': 'Preço por m² ($)',
        'herr_btn_calc_metros': 'Calcular Preço Total',
        'herr_precio_total_label': 'Preço Total do Imóvel',
        'herr_calc3_titulo': '💰 Calculadora de Entrada',
        'herr_precio_propiedad': 'Preço Total ($)',
        'herr_porcentaje_enganche': '% de Entrada',
        'herr_btn_calc_enganche': 'Calcular Entrada',
        'herr_monto_enganche_label': 'Valor da Entrada',
        'herr_saldo_financiar_label': 'Saldo a Financiar',
        'stats_titulo': 'Estatísticas',
        'stats_volver': '← Voltar ao Painel',
        'stats_periodo_label': 'Período:',
        'stats_periodo_semana': '1 Semana',
        'stats_periodo_mes': '1 Mês',
        'stats_periodo_anio': '1 Ano',
        'stats_periodo_todo': 'Todo o Tempo',
        'stats_pdf_semana': 'PDF 1 Semana',
        'stats_pdf_mes': 'PDF 1 Mês',
        'stats_pdf_anio': 'PDF 1 Ano',
        'stats_pdf_todo': 'PDF Tudo',
        'stats_total_leads': 'Total de Leads',
        'stats_leads_mes': 'Leads Este Mês',
        'stats_tasa_conversion': 'Taxa de Conversão',
        'stats_chart_zona': 'Leads por Zona',
        'stats_chart_clasificacion': 'Leads por Classificação',
        'inv_titulo_pagina': 'Inventário de Imóveis',
        'inv_btn_agregar': 'Adicionar Imóvel',
        'inv_btn_volver': 'Voltar',
        'inv_buscar_placeholder': 'Buscar por título ou localização...',
        'inv_vacio_titulo': 'Nenhum imóvel ainda',
        'inv_vacio_texto': 'Comece adicionando seu primeiro imóvel',
        'inv_sin_resultados_titulo': 'Sem resultados',
        'inv_sin_resultados_texto': 'Não encontramos imóveis com esse critério',
        'inv_sin_descripcion': 'Sem descrição',
        'inv_btn_ver': 'Ver',
        'inv_btn_editar': 'Editar',
        'inv_confirmar_eliminar': 'Excluir este imóvel?',
        'inv_modal_agregar_titulo': 'Adicionar Novo Imóvel',
        'inv_modal_editar_titulo': 'Editar Imóvel',
        'inv_label_titulo': 'Título *',
        'inv_placeholder_titulo': 'Ex: Casa na Zona 10',
        'inv_label_descripcion': 'Descrição',
        'inv_placeholder_descripcion': 'Detalhes do imóvel...',
        'inv_label_precio': 'Preço (USD) *',
        'inv_label_ubicacion': 'Localização *',
        'inv_placeholder_ubicacion': 'Ex: Zona 14, Guatemala',
        'inv_label_habitaciones': 'Quartos',
        'inv_label_banos': 'Banheiros',
        'inv_label_m2': 'm²',
        'inv_label_fotos': 'Fotos (máx. 5)',
        'inv_upload_click': 'Clique para enviar fotos',
        'inv_upload_sub': 'JPG, PNG, WEBP · Você pode enviar várias vezes',
        'inv_upload_click_editar': 'Clique para adicionar mais fotos',
        'inv_upload_sub_editar': 'Você pode enviar várias vezes',
        'inv_btn_guardar': 'Salvar Imóvel',
        'inv_btn_guardar_cambios': 'Salvar Alterações',
        'inv_subiendo_fotos': 'Enviando fotos...',
        'inv_guardando': 'Salvando...',
        'inv_optimizando': 'Otimizando fotos...',
        'inv_fotos_actuales': 'Fotos atuais',
        'inv_foto_label': 'Foto',
        'inv_sin_fotos': 'Sem fotos ainda',
        'inv_info_agrega': 'As novas fotos serão adicionadas às existentes (máx. 5 no total)',
        'inv_espacio_max': 'Você atingiu o máximo de 5 fotos',
        'inv_espacio_restante': 'Você pode adicionar mais {n} foto(s)',
        'inv_alert_max': 'Você já tem o máximo de 5 fotos. Remova uma para adicionar outra.',
        'inv_alert_parcial': 'Apenas {n} foto(s) foram adicionadas. Máximo de 5 fotos por imóvel.',
        'inv_detalle_precio': 'Preço',
        'inv_detalle_ubicacion': 'Localização',
        'temp_MUY_CALIENTE': '🔥 MUITO QUENTE', 'temp_CALIENTE': '🔥 QUENTE', 'temp_MEDIO': '🟡 MÉDIO', 'temp_FRIO': '❄️ FRIO',
        'class_💎 VIP / INVERSIONISTA': 'ALTO VALOR 💎',
        'class_🔥 PROSPECTO A': 'PROSPECTO 🟡',
        'class_🟡 SEGUIMIENTO B': 'ACOMPANHAMENTO ⚪',
        'class_❄️ LEAD FRÍO': 'LEAD FRIO ❄️',
        'class_❄️ LEAD FRIO': 'LEAD FRIO ❄️',
        'class_💎 CLIENTE': 'CLIENTE 💎',
    },
    'zh': {
        'titulo_form': '请填写您的联系方式',
        'placeholder_nombre': '全名',
        'placeholder_tel': '电话号码',
        'placeholder_zona': '感兴趣的区域',
        'placeholder_presupuesto': '预算 (美元)',
        'placeholder_propiedad': '您在寻找什么样的房产？',
        'boton_enviar': '发送信息',
        'mensaje_exito': '已收到！',
        'subtitulo_exito': '我们会尽快与您联系。',
        'login_titulo': '房地产访问',
        'login_boton': '登录',
        'historial_titulo': '潜客仪表板',
        'acepto_terminos': '我接受隐私政策。',
        'selecciona_idioma': '选择您的语言',
        'col_fecha': '日期',
        'col_clasificacion': '分类',
        'col_temperatura': '优先级',
        'col_mensaje': '信息',
        'col_acciones': '操作',
        'col_score': '评分',
        'btn_descargar': '下载 Excel',
        'btn_buscar': '按姓名搜索...',
        'btn_limpiar': '清除',
        'no_leads': '未找到潜客。',
        'btn_es': '西班牙语', 'btn_en': '英语', 'btn_fr': '法语', 'btn_de': '德语', 'btn_pt': '葡萄牙语', 'btn_zh': '中文',
        'btn_marcar_cliente': '客户',
        'btn_desmarcar': '取消标记',
        'confirm_marcar': '将 {nombre} 标记为客户？',
        'confirm_desmarcar': '取消将 {nombre} 标记为客户？',
        'btn_inventario': '📦 库存',
        'btn_herramientas': '🧮 工具',
        'btn_estadisticas': '📈 统计',
        'btn_cerrar_sesion': '🔒 退出登录',
        'msg_cerrar_sesion': '为了安全，请记得使用完毕后退出登录',
        'btn_whatsapp': '通过WhatsApp联系',
        'btn_ver_propiedades': '查看可用房产',
        'pdf_reporte': '潜客报告',
        'pdf_periodo': '周期',
        'pdf_fecha': '日期',
        'pdf_col_fecha': '日期', 'pdf_col_nombre': '姓名', 'pdf_col_telefono': '电话',
        'pdf_col_zona': '区域', 'pdf_col_presupuesto': '预算', 'pdf_col_clasificacion': '分类',
        'pdf_col_score': '评分', 'pdf_col_temperatura': '优先级',
        'herr_titulo': '房地产工具',
        'herr_volver': '← 返回',
        'herr_calc1_titulo': '📈 多年收益率',
        'herr_precio_inicial': '初始价格 ($)',
        'herr_rentabilidad_anual': '年收益率 %',
        'herr_anos_proyectar': '预测年数',
        'herr_btn_calc_rentabilidad': '计算收益率',
        'herr_tabla_anio': '年份',
        'herr_tabla_valor': '价值',
        'herr_tabla_ganancia': '收益',
        'herr_calc2_titulo': '📐 每平方米价格',
        'herr_metraje': '面积 (m²)',
        'herr_precio_m2': '每平方米价格 ($)',
        'herr_btn_calc_metros': '计算总价',
        'herr_precio_total_label': '房产总价',
        'herr_calc3_titulo': '💰 首付计算器',
        'herr_precio_propiedad': '总价 ($)',
        'herr_porcentaje_enganche': '首付比例 %',
        'herr_btn_calc_enganche': '计算首付',
        'herr_monto_enganche_label': '首付金额',
        'herr_saldo_financiar_label': '待融资余额',
        'stats_titulo': '统计数据',
        'stats_volver': '← 返回仪表板',
        'stats_periodo_label': '周期：',
        'stats_periodo_semana': '1 周',
        'stats_periodo_mes': '1 个月',
        'stats_periodo_anio': '1 年',
        'stats_periodo_todo': '全部时间',
        'stats_pdf_semana': 'PDF 1 周',
        'stats_pdf_mes': 'PDF 1 个月',
        'stats_pdf_anio': 'PDF 1 年',
        'stats_pdf_todo': 'PDF 全部',
        'stats_total_leads': '潜客总数',
        'stats_leads_mes': '本月潜客',
        'stats_tasa_conversion': '转化率',
        'stats_chart_zona': '按区域分类的潜客',
        'stats_chart_clasificacion': '按分类统计的潜客',
        'inv_titulo_pagina': '房产库存',
        'inv_btn_agregar': '添加房产',
        'inv_btn_volver': '返回',
        'inv_buscar_placeholder': '按标题或位置搜索...',
        'inv_vacio_titulo': '暂无房产',
        'inv_vacio_texto': '开始添加您的第一个房产',
        'inv_sin_resultados_titulo': '无结果',
        'inv_sin_resultados_texto': '未找到符合条件的房产',
        'inv_sin_descripcion': '无描述',
        'inv_btn_ver': '查看',
        'inv_btn_editar': '编辑',
        'inv_confirmar_eliminar': '删除此房产？',
        'inv_modal_agregar_titulo': '添加新房产',
        'inv_modal_editar_titulo': '编辑房产',
        'inv_label_titulo': '标题 *',
        'inv_placeholder_titulo': '例如：10区的房子',
        'inv_label_descripcion': '描述',
        'inv_placeholder_descripcion': '房产详情...',
        'inv_label_precio': '价格 (美元) *',
        'inv_label_ubicacion': '位置 *',
        'inv_placeholder_ubicacion': '例如：危地马拉14区',
        'inv_label_habitaciones': '卧室',
        'inv_label_banos': '浴室',
        'inv_label_m2': '平方米',
        'inv_label_fotos': '照片（最多5张）',
        'inv_upload_click': '点击上传照片',
        'inv_upload_sub': 'JPG、PNG、WEBP · 可多次上传',
        'inv_upload_click_editar': '点击添加更多照片',
        'inv_upload_sub_editar': '可多次上传',
        'inv_btn_guardar': '保存房产',
        'inv_btn_guardar_cambios': '保存更改',
        'inv_subiendo_fotos': '正在上传照片...',
        'inv_guardando': '正在保存...',
        'inv_optimizando': '正在优化照片...',
        'inv_fotos_actuales': '当前照片',
        'inv_foto_label': '照片',
        'inv_sin_fotos': '暂无照片',
        'inv_info_agrega': '新照片将添加到现有照片中（共最多5张）',
        'inv_espacio_max': '您已达到5张照片的上限',
        'inv_espacio_restante': '您还可以添加 {n} 张照片',
        'inv_alert_max': '您已达到5张照片的上限。请删除一张以添加新照片。',
        'inv_alert_parcial': '仅添加了 {n} 张照片。每个房产最多5张照片。',
        'inv_detalle_precio': '价格',
        'inv_detalle_ubicacion': '位置',
        'temp_MUY_CALIENTE': '🔥 非常热', 'temp_CALIENTE': '🔥 热', 'temp_MEDIO': '🟡 中等', 'temp_FRIO': '❄️ 冷',
        'class_💎 VIP / INVERSIONISTA': '高价值 💎',
        'class_🔥 PROSPECTO A': '潜在客户 🟡',
        'class_🟡 SEGUIMIENTO B': '跟进中 ⚪',
        'class_❄️ LEAD FRÍO': '冷淡客户 ❄️',
        'class_❄️ LEAD FRIO': '冷淡客户 ❄️',
        'class_💎 CLIENTE': '客户 💎',
    }
}
