DICCIONARIO = {
    'es': {
        'titulo_form': 'Por favor, llena tus datos para contactarte.',
        'placeholder_nombre': 'Nombre completo',
        'placeholder_tel': 'Teléfono',
        'placeholder_zona': 'Zona de interés',
        'placeholder_presupuesto': 'Presupuesto USD',
        'placeholder_propiedad': '¿Qué propiedad busca?',
        'boton_enviar': 'Enviar Información',
        'mensaje_exito': '¡Recibido!',
        'subtitulo_exito': 'Nos pondremos en contacto pronto.',
        'login_titulo': 'Acceso Inmobiliaria',
        'historial_titulo': 'Dashboard de Leads',
        'acepto_terminos': 'Acepto el tratamiento de mis datos personales según la política de privacidad.',
        'selecciona_idioma': 'Selecciona tu idioma',
        'col_fecha': 'Fecha',
        'col_clasificacion': 'Clasificación',
        'col_temperatura': 'Temperatura',
        'col_mensaje': 'Mensaje',
        'btn_descargar': 'Descargar Excel',
        'btn_buscar': 'Buscar por nombre...',
        'btn_limpiar': 'Limpiar',
        'no_leads': 'No hay prospectos.'
    },
    'en': {
        'titulo_form': 'Please fill in your details to contact you.',
        'placeholder_nombre': 'Full Name',
        'placeholder_tel': 'Phone Number',
        'placeholder_zona': 'Area of interest',
        'placeholder_presupuesto': 'Budget USD',
        'placeholder_propiedad': 'What property are you looking for?',
        'boton_enviar': 'Send Information',
        'mensaje_exito': 'Received!',
        'subtitulo_exito': 'We will contact you soon.',
        'login_titulo': 'Real Estate Access',
        'historial_titulo': 'Leads Dashboard',
        'acepto_terminos': 'I accept the processing of my personal data according to the privacy policy.',
        'selecciona_idioma': 'Select your language',
        'col_fecha': 'Date',
        'col_clasificacion': 'Classification',
        'col_temperatura': 'Temperature',
        'col_mensaje': 'Message',
        'btn_descargar': 'Download Excel',
        'btn_buscar': 'Search by name...',
        'btn_limpiar': 'Clear',
        'no_leads': 'No leads found.'
    },
    'fr': {
        'titulo_form': 'Veuillez remplir vos coordonnées.',
        'placeholder_nombre': 'Nom complet',
        'placeholder_tel': 'Téléphone',
        'placeholder_zona': "Zone d'intérêt",
        'placeholder_presupuesto': 'Budget USD',
        'placeholder_propiedad': 'Quelle propriété recherchez-vous?',
        'boton_enviar': 'Envoyer les informations',
        'mensaje_exito': 'Reçu!',
        'subtitulo_exito': 'Nous vous contacterons bientôt.',
        'login_titulo': 'Accès Immobilier',
        'historial_titulo': 'Tableau de bord des prospects',
        'acepto_terminos': "J'accepte le traitement de mes données conformément à la confidentialité.",
        'selecciona_idioma': 'Choisissez votre langue',
        'col_fecha': 'Date',
        'col_clasificacion': 'Classification',
        'col_temperatura': 'Température',
        'col_mensaje': 'Message',
        'btn_descargar': 'Télécharger Excel',
        'btn_buscar': 'Chercher par nom...',
        'btn_limpiar': 'Effacer',
        'no_leads': 'Aucun prospect trouvé.'
    },
    'de': {
        'titulo_form': 'Bitte füllen Sie Ihre Daten aus.',
        'placeholder_nombre': 'Vollständiger Name',
        'placeholder_tel': 'Telefonnummer',
        'placeholder_zona': 'Interessengebiet',
        'placeholder_presupuesto': 'Budget USD',
        'placeholder_propiedad': 'Welche Immobilie suchen Sie?',
        'boton_enviar': 'Infos Senden',
        'mensaje_exito': 'Empfangen!',
        'subtitulo_exito': 'Wir werden uns bald melden.',
        'login_titulo': 'Immobilien Zugang',
        'historial_titulo': 'Leads Dashboard',
        'acepto_terminos': 'Ich akzeptiere die Verarbeitung meiner Daten.',
        'selecciona_idioma': 'Wählen Sie Ihre Sprache',
        'col_fecha': 'Datum',
        'col_clasificacion': 'Klassifizierung',
        'col_temperatura': 'Temperatur',
        'col_mensaje': 'Nachricht',
        'btn_descargar': 'Excel Herunterladen',
        'btn_buscar': 'Nach Name suchen...',
        'btn_limpiar': 'Löschen',
        'no_leads': 'Keine Leads gefunden.'
    },
    'pt': {
        'titulo_form': 'Por favor, preencha seus dados para contato.',
        'placeholder_nombre': 'Nome completo',
        'placeholder_tel': 'Telefone',
        'placeholder_zona': 'Zona de interesse',
        'placeholder_presupuesto': 'Orçamento USD',
        'placeholder_propiedad': 'Que tipo de imóvel procura?',
        'boton_enviar': 'Enviar Informações',
        'mensaje_exito': 'Recebido!',
        'subtitulo_exito': 'Entraremos em contato em breve.',
        'login_titulo': 'Acesso Imobiliário',
        'historial_titulo': 'Painel de Leads',
        'acepto_terminos': 'Aceito o tratamento dos meus datos.',
        'selecciona_idioma': 'Selecione seu idioma',
        'col_fecha': 'Data',
        'col_clasificacion': 'Classificação',
        'col_temperatura': 'Temperatura',
        'col_mensaje': 'Mensagem',
        'btn_descargar': 'Baixar Excel',
        'btn_buscar': 'Buscar por nome...',
        'btn_limpiar': 'Limpar',
        'no_leads': 'Nenhum lead encontrado.'
    },
    'zh': {
        'titulo_form': '请填写您的联系方式',
        'placeholder_nombre': '全名',
        'placeholder_tel': '电话号码',
        'placeholder_zona': '感兴趣的区域',
        'placeholder_presupuesto': '预算 (美元)',
        'placeholder_propiedad': '您在寻找什么样的房产？',
        'boton_enviar': '发送信息',
        'mensaje_exito': '已收到！',
        'subtitulo_exito': '我们会尽快与您联系。',
        'login_titulo': '房地产访问',
        'historial_titulo': '潜客仪表板',
        'acepto_terminos': '我接受隐私政策。',
        'selecciona_idioma': '选择您的语言',
        'col_fecha': '日期',
        'col_clasificacion': '分类',
        'col_temperatura': '温度',
        'col_mensaje': '信息',
        'btn_descargar': '下载 Excel',
        'btn_buscar': '按姓名搜索...',
        'btn_limpiar': '清除',
        'no_leads': '未找到潜客。'
    }
}
